# Standard Library Imports
from typing import Any, Dict

# Third Party Imports
from treelib import Tree

# RAMSTK Package Imports
from ramstk.controllers import RAMSTKDataManager as RAMSTKDataManager

class DataManager(RAMSTKDataManager):
    _tag: str = ...
    _environment_tree: Any = ...
    _mission_tree: Any = ...
    _mission_phase_tree: Any = ...
    last_id: Any = ...

    def __init__(self, **kwargs: Dict[Any, Any]) -> None:
        ...

    def on_select_all(self) -> None:
        ...

    def _do_load_environments(self, phase_id: int, parent_id: str) -> None:
        ...

    def _do_load_missions(self) -> None:
        ...

    def _do_load_mission_phases(self, mission_id: int) -> None:
        ...

    def _do_set_tree(self, tree: Tree) -> None:
        ...

    def _on_insert(self, tree: Tree, node_id: Any) -> None:
        ...
