# Standard Library Imports
from typing import Any, Dict, List

# RAMSTK Package Imports
from ramstk.views.gtk3 import _ as _
from ramstk.views.gtk3.widgets import RAMSTKComboBox as RAMSTKComboBox
from ramstk.views.gtk3.widgets import RAMSTKEntry as RAMSTKEntry
from ramstk.views.gtk3.widgets import RAMSTKFixedPanel as RAMSTKFixedPanel

class ICDesignElectricInputPanel(RAMSTKFixedPanel):
    _dic_technology: Dict[int, List[Any]]
    _dic_types: Dict[int, List[Any]]
    _select_msg: str
    _tag: str
    _title: Any
    cmbApplication: Any
    cmbConstruction: Any
    cmbECC: Any
    cmbManufacturing: Any
    cmbPackage: Any
    cmbQuality: Any
    cmbTechnology: Any
    cmbType: Any
    txtArea: Any
    txtFeatureSize: Any
    txtNActivePins: Any
    txtNCycles: Any
    txtNElements: Any
    txtOperatingLife: Any
    txtThetaJC: Any
    txtVoltageESD: Any
    txtYearsInProduction: Any
    dic_attribute_index_map: Any
    dic_attribute_widget_map: Any
    def __init__(self) -> None: ...
    def do_load_comboboxes(self, subcategory_id: int) -> None: ...
    def _do_set_sensitive(self) -> None: ...
    def _do_load_application_combo(self, attributes: Dict[str, Any]) -> None: ...
    def __do_load_dram(self, attributes: Dict[str, Any]) -> None: ...
    def __do_load_eeprom(self, attributes: Dict[str, Any]) -> None: ...
    def __do_load_gaas(self, attributes: Dict[str, Any]) -> None: ...
    def __do_load_linear(self, attributes: Dict[str, Any]) -> None: ...
    def __do_load_logic(self, attributes: Dict[str, Any]) -> None: ...
    def __do_load_microprocessor_microcontroller(
        self, attributes: Dict[str, Any]
    ) -> None: ...
    def __do_load_pal_pla(self, attributes: Dict[str, Any]) -> None: ...
    def __do_load_rom(self, attributes: Dict[str, Any]) -> None: ...
    def __do_load_sram(self, attributes: Dict[str, Any]) -> None: ...
    def __do_load_vhsic_vlsi(self, attributes: Dict[str, Any]) -> None: ...
    def __do_set_dram_sensitive(self) -> None: ...
    def __do_set_eeprom_sensitive(self) -> None: ...
    def __do_set_gaas_sensitive(self) -> None: ...
    def __do_set_linear_sensitive(self) -> None: ...
    def __do_set_logic_sensitive(self) -> None: ...
    def __do_set_microprocessor_microcontroller_sensitive(self) -> None: ...
    def __do_set_pal_pla_sensitive(self) -> None: ...
    def __do_set_rom_sensitive(self) -> None: ...
    def __do_set_sram_sensitive(self) -> None: ...
    def __do_set_vhsic_vlsi_sensitive(self) -> None: ...
