Working:
  In Progress:
    - "inprogress"
  Done:
    - "closed"
Backlog:
  Needs Triage:
    - "globalbacklog"
  Low Priority:
    - "globalbacklog"
    - "low"
  Normal Priority:
    - "globalbacklog"
    - "normal"
  High Priority:
    - "globalbacklog"
    - "high"
