branchName: short
branches:
  - label: 'type: build'
    prefix: build/
  - label: 'type: chore'
    prefix: chore/
  - label: 'type: ci'
    prefix: ci/
  - label: 'type: docs'
    prefix: docs/
  - label: 'type: feature'
    prefix: feature/
  - label: 'type: fix'
    prefix: fix/
  - label: 'type: refactor'
    prefix: refactor/
  - label: 'type: style'
    prefix: style/
  - label: 'type: test'
    prefix: test/
  - label: '*'
    skip: true
