'bump: minor': ['feature/*', 'feat/*']
'bump: patch': ['fix/*', 'bugfix/*', 'hotfix/*', 'enhance/*']
'type: build': ['build/*']
'type: ci': ['ci/*', 'dependabot/*', 'imgbot']
'type: docs': ['doc/*', 'docs/*']
'type: feature': ['feature/*', 'feat/*']
'type: fix': ['fix/*', 'bugfix/*', 'hotfix/*']
'type: refactor': ['refactor/*']
'type: style': ['style/*']
'type: test': ['test/*', 'tests/*']
'Release': ['release/*']
