feature: ['feature/*', 'feat/*']
minor: ['feature/*', 'feat/*']
bug: ['fix/*', 'bugfix/*', 'hotfix/*']
patch: ['fix/*', 'bugfix/*', 'hotfix/*', 'enhance/*']
chore: ['chore/*', 'test/*', 'tests/*', 'refactor/*', 'imgbot']
quality: ['test/*', 'tests/*', 'refactor/*']
enhancement: ['enhance/*']
docs: ['doc/*', 'docs/*']
