name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  ## What Is Changing

  $CHANGES
categories:
  - title: 'Bug Fixes'
    labels:
      - 'bug'
  - title: 'Features'
    labels:
      - 'enhancement'
  - title: 'Maintenance'
    labels:
      - 'quality'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
