name-template: '$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'Bug Fixes'
    labels:
      - 'type: fix'
      - 'bump: patch'
  - title: 'Features'
    labels:
      - 'type: feature'
      - 'bump: minor'
  - title: 'Maintenance'
    labels:
      - 'type: build'
      - 'type: ci'
      - 'type: refactor'
change-template: '- [#$NUMBER] $TITLE  (@$AUTHOR)'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'bump: major'
  minor:
    labels:
      - 'bump: minor'
  patch:
    labels:
      - 'bump: patch'
  default: patch
exclude-labels:
  - 'type: chore'
  - 'dependencies'
  - 'type: docs'
  - 'endgame: duplicate'
  - 'endgame: invalid'
  - 'endgame: wontfix'
  - 'type: test'
  - 'Release'
template: |
  ## What Changed

  $CHANGES
