name-template: '$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  ## What Is Changing

  $CHANGES
categories:
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bug'
  - title: 'Features'
    labels:
      - 'feature'
      - 'minor'
  - title: 'Maintenance'
    labels:
      - 'quality'
      - 'enhancement'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: minor
exclude-labels:
  - 'chore'
  - 'dependencies'
  - 'docs'
  - 'duplicate'
  - 'invalid'
  - 'test'
