name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  ## Changes

  $CHANGES
categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'feat'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
  - title: 'Maintenance'
    labels:
      - 'refactor'
      - 'chore'
      - 'test'
  - title: 'Documentation'
    labels:
      - 'docs'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

