# Do not add WIP labels for PRs that are set to be work-in-progress.
addWipLabel: false

# Configuration for labels, set ignore to true to skip adding label
labels:
  wip:
    name: "🚧 WIP"
    color: "#FBCA04"
    description: "Still work-in-progress, please don't review and don't merge"
    ignore: true
  unreviewed:
    name: "🔍 Ready for Review"
    color: "#334796"
    description: "Pull Request is not reviewed yet"
    ignore: true
  approved:
    name: "✅ Approved"
    color: "#0E8A16"
    description: "Pull Request has been approved and can be merged"
    ignore: true
  needsMoreApprovals:
    name: "🌟 Needs more Approvals"
    color: "#96C823"
    description: "Pull Request needs more approvals"
    ignore: true
  changesRequested:
    name: "⚠️ Changes requested"
    color: "#AA2626"
    description: "Pull Request needs changes before it can be reviewed again"
    ignore: true
  merged:
    name: "endgame: merged"
    color: "#C2E0C6"
    description: "Pull Request has been merged successfully"
    ignore: false
  closed:
    name: "status: closed"
    color: "#0E8A16"
    description: "Pull Request is complete and integrated or closed for anther reason."
    ignore: false
