repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v2.2.3
        hooks:
            -   id: check-docstring-first
            -   id: check-merge-conflict
            -   id: check-xml
            -   id: debug-statements
            -   id: end-of-file-fixer
            -   id: no-commit-to-branch
            -   id: requirements-txt-fixer
            -   id: trailing-whitespace
    -   repo: https://github.com/python/black
        rev: stable
        hooks:
            -   id: black
                language_version: python3.7
    -   repo: https://github.com/pre-commit/mirrors-pylint
        rev: v2.3.1
        hooks:
            -   id: pylint
    -   repo: https://github.com/pre-commit/mirrors-isort
        rev: v4.3.20
        hooks:
            -   id: isort
