repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
          - id: check-docstring-first
          - id: check-merge-conflict
          - id: check-toml
          - id: check-yaml
          - id: debug-statements
          - id: end-of-file-fixer
          - id: no-commit-to-branch
          - id: trailing-whitespace
    - repo: https://github.com/psf/black
      rev: '21.7b0'
      hooks:
        - id: black
          types_or: [python, pyi]
          language_version: python3
    - repo: https://github.com/PyCQA/isort
      rev: 5.9.3
      hooks:
        - id: isort
          args: [--settings-file, ./pyproject.toml]
    - repo: https://github.com/weibullguy/docformatter
      rev: v1.5
      hooks:
        - id: docformatter
          additional_dependencies: [tomli]
          args: [--in-place, --config, ./pyproject.toml]
    - repo: https://github.com/weibullguy/pycodestyle
      rev: '2.6.1'
      hooks:
        - id: pycodestyle
          args: [--config, ./setup.cfg]
    - repo: https://github.com/pycqa/pydocstyle
      rev: 6.1.1
      hooks:
        - id: pydocstyle
          args: [--config, ./setup.cfg]
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.910
      hooks:
        - id: mypy
          additional_dependencies: [types-python-dateutil]
          args: [--config-file, ./pyproject.toml]
    - repo: https://github.com/pre-commit/mirrors-pylint
      rev: v3.0.0a4
      hooks:
          - id: pylint
            args: [-d, E0401, -f, colorized, --rcfile, ./pyproject.toml]
    - repo: https://github.com/myint/eradicate
      rev: 'v2.0.0'
      hooks:
        - id: eradicate
          args: []
    -   repo: local
        hooks:
        -   id: wily
            name: wily
            entry: wily diff
            verbose: true
            language: python
            additional_dependencies: [wily]
            args: [--no-detail]
    - repo: https://github.com/weibullguy/rstcheck
      rev: 'v3.3.2'
      hooks:
        - id: rstcheck
          args: [-r, --config, ./pyproject.toml]
