repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
          - id: check-docstring-first
          - id: check-merge-conflict
          - id: check-xml
          - id: debug-statements
          - id: end-of-file-fixer
          - id: no-commit-to-branch
          - id: trailing-whitespace
    - repo: git://github.com/FalconSocial/pre-commit-mirrors-pep257
      rev: v0.3.3
      hooks:
        - id: pep257
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.782
      hooks:
        - id: mypy
          args: [--config-file, ./setup.cfg]
    - repo: https://github.com/pre-commit/mirrors-pylint
      rev: v2.6.0
      hooks:
          - id: pylint
            args: [-d, E0401, -f, colorized, --ignore-patterns, 'test_*?.py']
