repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.4.0
      hooks:
          - id: check-docstring-first
          - id: check-merge-conflict
          - id: check-toml
          - id: check-yaml
          - id: debug-statements
          - id: end-of-file-fixer
          - id: no-commit-to-branch
          - id: trailing-whitespace
    - repo: https://github.com/pre-commit/mirrors-yapf
      rev: 'v0.30.0'
      hooks:
        - id: yapf
          args: [--style, ./setup.cfg]
    - repo: https://github.com/PyCQA/isort
      rev: 5.7.0
      hooks:
        - id: isort
          args: [--settings-file, ./pyproject.toml]
    - repo: https://github.com/myint/docformatter
      rev: 'v1.4'
      hooks:
        - id: docformatter
          args: [-c]
    - repo: https://github.com/weibullguy/pycodestyle
      rev: 2.6.1
      hooks:
        - id: pycodestyle
          args: [--config, ./setup.cfg]
    - repo: https://github.com/pycqa/pydocstyle
      rev: 5.1.1
      hooks:
        - id: pydocstyle
          args: [--config, ./setup.cfg]
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.790
      hooks:
        - id: mypy
          args: [--config-file, ./setup.cfg]
    - repo: https://github.com/pre-commit/mirrors-pylint
      rev: v2.6.0
      hooks:
          - id: pylint
            args: [-d, E0401, -f, colorized, --rcfile, ./pyproject.toml]
    - repo: https://github.com/myint/eradicate
      rev: 'v2.0.0'
      hooks:
        - id: eradicate
          args: []
    - repo: https://github.com/mgedmin/check-manifest
      rev: '0.46'
      hooks:
        - id: check-manifest
