repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
          - id: check-docstring-first
          - id: check-merge-conflict
          - id: debug-statements
          - id: end-of-file-fixer
          - id: no-commit-to-branch
          - id: trailing-whitespace
    - repo: https://github.com/pycqa/pydocstyle
      rev: 5.1.1
      hooks:
        - id: pydocstyle
          args: [--config, ./setup.cfg]
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.782
      hooks:
        - id: mypy
          args: [--config-file, ./setup.cfg]
    - repo: https://github.com/pre-commit/mirrors-pylint
      rev: v2.6.0
      hooks:
          - id: pylint
            args: [-d, E0401, -f, colorized, --rcfile, ./setup.cfg]
