dist: xenial
sudo: required
language: python

python:
    - "3.7"

#virtualenv:
#  system_site_packages: true

#before_install:
#    python3 -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); fcntl.fcntl(sys.stdout, fcntl.F_SETFL, flags&~os.O_NONBLOCK);'

install:
    - sudo apt-get update
    - pip install -U pip
    - pip install -U setuptools>12.0
    - pip install -U urllib3
    - pip install --only-binary=numpy numpy==1.16.3
    - pip install --only-binary=scipy scipy==1.2.1
    - pip install -r requirements_run.txt
    - pip install -r requirements_dev.txt
    - python setup.py install

# Command to run tests.
script:
    - python setup.py test

# After the build was successful what to do?
after_success:
    - coveralls
    - python-codacy-coverage -r coverage.xml

# What's the environment look like if the build fails silently.
after_failure:
    - pip freeze
    - ls ~/virtualenv/python$TRAVIS_PYTHON_VERSION/lib/python3.7/site-packages
