language: python
python:
    - "2.6"
    - "2.7"

# Command to install dependencies.
install: 
    - "pip install -U pip"
    - "pip install ."
    - "pip install --only-binary=numpy,scipy -r devtools/requirements.txt"

# Command to run tests.
#script: 
    #    - nosetests -v --attr=unit=True --with-coverage --cover-branches
      #    - nosetests -v --attr=integration=True --with-coverage --cover-branches
