language: python
python:
    - "2.6"
    - "2.7"
# Command to install dependencies.
install: 
    - "pip install ."
    - "pip install -r devtools/requirements.txt"

# Command to run tests.
# script: devtools/py.test
