dist: xenial
sudo: required
language: python
services:
    - postgresql
    - xvfb

python:
    - "3.6"
    - "3.7"

env:
    system_site_packages: true

install:
    - sudo apt-get update
    - sudo apt-get install -y libgirepository1.0-dev gir1.2-gtk-3.0 python3-gi python3-gi-cairo python3-pytest libenchant1c2a libenchant-dev
    - pip install -U pip
    - pip install -U setuptools>12.0
    - pip install -U urllib3
    - pip install -U pip-tools
    - pip install -r requirements.txt -r requirements-test.txt
    - make install PREFIX=$VIRTUAL_ENV

# Setup database for testing.
before_script:
    - psql -c 'create database TestProgramDB;' -U postgres

# Command to run tests.  First the full test suite without coverage, then again
# with coverage.
script:
    - make test
    - make coverage

# After the build was successful what to do?
after_success:
    - coveralls

# What's the environment look like if the build fails silently.
after_failure:
    - pip freeze
    - ls ~/virtualenv/python$TRAVIS_PYTHON_VERSION/lib/python3.7/site-packages
