dist: trusty
sudo: required
language: python

python:
    - "2.7"
# Gotta use site packages so pygtk is available.
virtualenv:
  system_site_packages: true

install:
    - sudo apt-get update
    - sudo apt-get install -yqq python-gtk2 python-gtk2-dev
    - pip install -U pip
    - pip install -U setuptools>12.0
    - pip install --only-binary=numpy numpy==1.14.3
    - pip install --only-binary=scipy scipy==1.0.0
    - pip install coverage==4.0.3
    - pip install -r requirements_run.txt
    - pip install -r requirements_dev.txt
    - pip install matplotlib==1.4.3
    - python setup.py install

# Command to run tests.
script:
    - python setup.py test

# What's the environment look like if the build fails silently.
after_failure:
    - pip freeze
    - ls ~/virtualenv/python$TRAVIS_PYTHON_VERSION/lib/python2.7/site-packages
    - dpkg -L python-gtk2
