dist: xenial
sudo: required
language: python
services: xvfb

python:
    - "3.7"

env:
    system_site_packages: true

install:
    - sudo apt-get update
    - sudo apt-get install -y libgirepository1.0-dev gir1.2-gtk-3.0 python3-gi python3-gi-cairo python3-pytest
    - pip install -U pip
    - pip install -U setuptools>12.0
    - pip install -U urllib3
    - pip install --only-binary=numpy numpy==1.16.3
    - pip install --only-binary=scipy scipy==1.2.1
    - pip install -r requirements_run.txt
    - pip install -r requirements_dev.txt
    - make install

# Command to run tests.
script:
    - make test

# After the build was successful what to do?
after_success:
    - coveralls
    - python-codacy-coverage -r coverage.xml

# What's the environment look like if the build fails silently.
after_failure:
    - pip freeze
    - ls ~/virtualenv/python$TRAVIS_PYTHON_VERSION/lib/python3.7/site-packages
