language: python
python:
    - "2.7"

install:
    - sudo apt-get update
    # We do this conditionally because it saves us some downloading if the
    # version is the same.
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
        else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda config --append channels conda-forge
    - conda config --append channels rogerramos
    - conda update -q conda
    # Useful for debugging any issues with conda
    - conda info -a

    # Replace dep1 dep2 ... with your dependencies
    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pygtk defusedxml lifelines lxml numpy pandas scipy sortedcontainers sqlalchemy sqlalchemy-utils statsmodels xlrd xlwt coverage pytest pytest-cov python-coveralls nose
    - source activate test-environment
    - pip install matplotlib==1.4.3 pypubsub==3.3.0 treelib codacy-coverage
    - python setup.py install

# Command to run tests.
script:
    - python setup.py test

after_failure:
    - conda list
