language: python
python:
    - "2.7"

install:
    - sudo apt-get update
    - pip install -U setuptools>12.0
    - pip install pypubsub==3.3.0
    - pip install numpy==1.14.3
    - pip install coverage==4.0.3
    - pip install -r requirements_run.txt
    - pip install -r requirements_dev.txt
    # Now we have to install pygtk2.
    # Environment setup
    - export VIRT_ROOT=$HOME/virtualenv/python$TRAVIS_PYTHON_VERSION
    - export PKG_CONFIG_PATH=$VIRT_ROOT/lib/pkgconfig
    # Download tarballs.
    - wget http://www.cairographics.org/releases/py2cairo-1.10.0.tar.bz2
    - wget http://ftp.gnome.org/pub/GNOME/sources/pygobject/2.28/pygobject-2.28.6.tar.bz2
    - wget http://ftp.gnome.org/pub/GNOME/sources/pygtk/2.24/pygtk-2.24.0.tar.bz2
    # PyCairo
    - tar xf py2cairo-1.10.0.tar.bz2
    - cd py2cairo-1.10.0
    - ./waf configure --prefix=$VIRT_ROOT > /dev/null
    - ./waf build > /dev/null
    - ./waf install > /dev/null
    - cd ..
    # PyGobject
    - tar xf pygobject-2.28.6.tar.bz2
    - cd pygobject-2.28.6
    - ./configure --prefix=$VIRT_ROOT --disable-introspection > /dev/null
    - make > /dev/null
    - make install > /dev/null
    - cd ..
    # PyGtk
    - tar xf pygtk-2.24.0.tar.bz2
    - cd pygtk-2.24.0
    - ./configure --prefix=$VIRT_ROOT > /dev/null
    - make > /dev/null
    - make install > /dev/null
    - cd ..
    # Install matplotlib after pygtk so it builds the GDK backend.
    - pip install matplotlib==1.4.3
    - python setup.py install

# Command to run tests.
script:
    - python setup.py test
