language: python
python:
    - "2.7"

# Command to install dependencies.
install:
    - "pip install -U pip"
    - "pip install pipenv"
    - "pipenv lock -r > requirements.txt"
    - "pip install --only-binary numpy,scipy -r requirements.txt"
    - "pip install ."

# Command to run tests.
script:
    - sh tools/RunTests.sh

# If build is successful, run coveralls.
after_success:
    - coveralls
