dist: precise
sudo: required
language: python

python:
    - "2.7"
virtualenv:
  system_site_packages: true

install:
    - sudo apt-get update
    - sudo apt-get install -yqq libblas-dev liblapack-dev python-gtk2 python-gtk2-dev
    - pip install -U setuptools>12.0
    - pip install pypubsub==3.3.0
    - pip install numpy==1.14.3
    - pip install coverage==4.0.3
    - pip install -r requirements_run.txt
    - pip install -r requirements_dev.txt
    - pip install matplotlib==1.4.3
    - python setup.py install

# Command to run tests.
script:
    - python setup.py test

after_failure:
    - pip freeze
    - ls ~/virtualenv/python$TRAVIS_PYTHON_VERSION/lib/python2.7/site-packages
    - dpkg -L python-gtk2
