language: python
python:
    - "2.7"

# Command to install dependencies.
before_install:
    - "pip install -U pip"
    - "pip install --only-binary=numpy,scipy -r requirements.txt"
    - "pip install ."

# Command to run tests.
script:
    - "python setup.py test"

# If build is successful, run coveralls.
after_success:
    - coveralls --data_file=tools/reports/coverage/coverage.xml
