# Standard Library Imports
from typing import Any, Dict

# RAMSTK Package Imports
from ramstk.views.gtk3 import Gtk as Gtk
from ramstk.views.gtk3 import _ as _
from ramstk.views.gtk3.widgets import RAMSTKCheckButton as RAMSTKCheckButton
from ramstk.views.gtk3.widgets import RAMSTKDialog as RAMSTKDialog
from ramstk.views.gtk3.widgets import RAMSTKEntry as RAMSTKEntry
from ramstk.views.gtk3.widgets import RAMSTKPanel as RAMSTKPanel

class EditOptionsPanel(RAMSTKPanel):
    _dic_attribute_keys: Any = ...
    _lst_labels: Any = ...
    _title: Any = ...
    chkFunctions: Any = ...
    chkRequirements: Any = ...
    chkHardware: Any = ...
    chkSoftware: Any = ...
    chkRCM: Any = ...
    chkTesting: Any = ...
    chkIncident: Any = ...
    chkSurvival: Any = ...
    chkValidation: Any = ...
    chkHazards: Any = ...
    chkStakeholder: Any = ...
    chkAllocation: Any = ...
    chkSimilarItem: Any = ...
    chkFMEA: Any = ...
    chkPoF: Any = ...
    chkRBD: Any = ...
    chkFTA: Any = ...
    txtSiteID: Any = ...
    txtSiteName: Any = ...
    txtProductKey: Any = ...
    txtExpireDate: Any = ...
    _lst_widgets: Any = ...

    def __init__(self) -> None:
        ...

    def _do_load_panel(self, attributes: Dict[str, Any]) -> None:
        ...

    def __do_set_callbacks(self) -> None:
        ...

    def __do_set_properties(self) -> None:
        ...


class EditOptions(RAMSTKDialog):
    _pnlPanel: Any = ...

    def __init__(self, parent: object = ...) -> None:
        ...

    def _cancel(self, __button: Gtk.Button) -> Any:
        ...

    def __make_ui(self) -> None:
        ...
