# Standard Library Imports
from typing import Any

# RAMSTK Package Imports
from ramstk.configuration import (
    RAMSTKUserConfiguration as RAMSTKUserConfiguration
)
from ramstk.logger import RAMSTKLogManager as RAMSTKLogManager
from ramstk.utilities import integer_to_boolean as integer_to_boolean
from ramstk.utilities import string_to_boolean as string_to_boolean
from ramstk.views.gtk3 import Gdk as Gdk
from ramstk.views.gtk3 import GObject as GObject
from ramstk.views.gtk3 import Gtk as Gtk
from ramstk.views.gtk3.widgets import RAMSTKBaseView as RAMSTKBaseView
from ramstk.views.gtk3.widgets import RAMSTKComboBox as RAMSTKComboBox
from ramstk.views.gtk3.widgets import RAMSTKEntry as RAMSTKEntry
from ramstk.views.gtk3.widgets import RAMSTKFrame as RAMSTKFrame
from ramstk.views.gtk3.widgets import RAMSTKLabel as RAMSTKLabel
from ramstk.views.gtk3.widgets import (
    RAMSTKScrolledWindow as RAMSTKScrolledWindow
)
from ramstk.views.gtk3.widgets import do_make_buttonbox as do_make_buttonbox
from ramstk.views.gtk3.widgets import do_make_column as do_make_column
from ramstk.views.gtk3.widgets import (
    do_make_label_group as do_make_label_group
)
from ramstk.views.gtk3.widgets import do_make_text_cell as do_make_text_cell
from ramstk.views.gtk3.widgets import (
    do_make_toggle_cell as do_make_toggle_cell
)
from ramstk.views.gtk3.widgets import (
    do_set_cell_properties as do_set_cell_properties
)

class EditPreferences(Gtk.Window, RAMSTKBaseView):
    btnConfDir: Any = ...
    btnDataDir: Any = ...
    btnIconDir: Any = ...
    btnLogDir: Any = ...
    cmbModuleBookTabPosition: Any = ...
    cmbWorkBookTabPosition: Any = ...
    cmbListBookTabPosition: Any = ...
    cmbReportSize: Any = ...
    txtFRMultiplier: Any = ...
    txtDecimalPlaces: Any = ...
    txtMissionTime: Any = ...
    cmbFormatFiles: Any = ...
    tvwFormatFile: Any = ...
    btnRevisionBGColor: Any = ...
    btnRevisionFGColor: Any = ...
    btnFunctionBGColor: Any = ...
    btnFunctionFGColor: Any = ...
    btnRequirementsBGColor: Any = ...
    btnRequirementsFGColor: Any = ...
    btnHardwareBGColor: Any = ...
    btnHardwareFGColor: Any = ...
    btnSoftwareBGColor: Any = ...
    btnSoftwareFGColor: Any = ...
    btnValidationBGColor: Any = ...
    btnValidationFGColor: Any = ...
    btnIncidentBGColor: Any = ...
    btnIncidentFGColor: Any = ...
    btnTestingBGColor: Any = ...
    btnTestingFGColor: Any = ...

    def __init__(self, __widget: Gtk.ImageMenuItem,
                 configuration: RAMSTKUserConfiguration,
                 logger: RAMSTKLogManager, parent: object) -> None:
        ...
