# Standard Library Imports
from typing import Any, Dict

# Third Party Imports
from treelib import Tree

# RAMSTK Package Imports
from ramstk.controllers import RAMSTKDataManager as RAMSTKDataManager

class DataManager(RAMSTKDataManager):
    _tag: str = ...
    _mechanism_tree: Any = ...
    _opload_tree: Any = ...
    _opstress_tree: Any = ...
    _test_method_tree: Any = ...
    def __init__(self, **kwargs: Dict[str, Any]) -> None: ...
    def do_set_mechanism_tree(self, tree: Tree) -> None: ...
    def do_set_opload_tree(self, tree: Tree) -> None: ...
    def do_set_opstress_tree(self, tree: Tree) -> None: ...
    def do_set_test_method_tree(self, tree: Tree) -> None: ...
    def on_select_all(self) -> None: ...
    def _do_load_mechanisms(self) -> None: ...
    def _do_load_oploads(self, mechanism_id: int) -> None: ...
    def _do_load_opstress(self, load_id: int, parent_id: str) -> None: ...
    def _do_load_test_method(self, load_id: int, parent_id: str) -> None: ...
    def _on_insert(self, tree: Tree, node_id: int) -> None: ...
