# Standard Library Imports
from typing import Any, Dict

# RAMSTK Package Imports
from ramstk.controllers import RAMSTKDataManager as RAMSTKDataManager
from ramstk.exceptions import DataAccessError as DataAccessError
from ramstk.models.programdb import RAMSTKMechanism as RAMSTKMechanism
from ramstk.models.programdb import RAMSTKMode as RAMSTKMode
from ramstk.models.programdb import RAMSTKOpLoad as RAMSTKOpLoad
from ramstk.models.programdb import RAMSTKOpStress as RAMSTKOpStress
from ramstk.models.programdb import RAMSTKTestMethod as RAMSTKTestMethod

class DataManager(RAMSTKDataManager):
    _tag: str = ...
    _root: int = ...
    _pkey: Any = ...
    last_id: Any = ...

    def __init__(self, **kwargs: Dict[str, Any]) -> None:
        ...

    def do_get_tree(self) -> None:
        ...

    _revision_id: Any = ...
    _parent_id: Any = ...

    def do_select_all(self, attributes: Dict[str, Any]) -> None:
        ...

    def do_update(self, node_id: int) -> None:
        ...

    def _do_delete(self, node_id: int) -> None:
        ...

    def _do_insert_opload(self, parent_id: str) -> None:
        ...

    def _do_insert_opstress(self, parent_id: str) -> None:
        ...

    def _do_insert_testmethod(self, parent_id: str) -> None:
        ...

    def _do_select_all_mechanism(self, mode_id: int) -> None:
        ...

    def _do_select_all_opload(self, parent_id: str) -> None:
        ...

    def _do_select_all_opstress(self, parent_id: str) -> None:
        ...

    def _do_select_all_testmethod(self, parent_id: str) -> None:
        ...
