from ramstk.configuration import RAMSTKUserConfiguration as RAMSTKUserConfiguration
from ramstk.logger import RAMSTKLogManager as RAMSTKLogManager
from ramstk.views.gtk3 import Gtk as Gtk
from ramstk.views.gtk3.widgets import RAMSTKComboBox as RAMSTKComboBox, RAMSTKEntry as RAMSTKEntry, RAMSTKPanel as RAMSTKPanel, RAMSTKWorkView as RAMSTKWorkView
from typing import Any

class GoalMethodPanel(RAMSTKPanel):
    cmbAllocationGoal: Any = ...
    cmbAllocationMethod: Any = ...
    txtHazardRateGoal: Any = ...
    txtMTBFGoal: Any = ...
    txtReliabilityGoal: Any = ...
    def __init__(self) -> None: ...

class AllocationPanel(RAMSTKPanel):
    def __init__(self) -> None: ...
    def do_set_callbacks(self) -> None: ...

class Allocation(RAMSTKWorkView):
    def __init__(self, configuration: RAMSTKUserConfiguration, logger: RAMSTKLogManager) -> None: ...
