# Stubs for ramstk.views.gtk3.books.listbook (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

# RAMSTK Package Imports
from ramstk.configuration import RAMSTKUserConfiguration
from ramstk.logger import RAMSTKLogManager
from ramstk.views.gtk3.widgets import RAMSTKBaseBook

class RAMSTKListBook(RAMSTKBaseBook):

    def __init__(self, configuration: RAMSTKUserConfiguration, logger: RAMSTKLogManager) -> None:
        self._dic_list_views = None
        ...

    def _on_close(self):
        pass

    def _on_module_change(self, module: str = ''):
        pass

    def insert_page(self, _list, hbx_tab_label, param):
        pass
