# Stubs for ramstk.views.gtk3.books.workbook (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ramstk.configuration import RAMSTKUserConfiguration
from ramstk.logger import RAMSTKLogManager
from ramstk.views.gtk3.widgets import RAMSTKBaseBook

class RAMSTKWorkBook(RAMSTKBaseBook):
    def __init__(self, configuration: RAMSTKUserConfiguration, logger: RAMSTKLogManager) -> None:
        self._dic_work_views = None
        ...

    def _on_module_change(self, module: str = ''):
        pass

    def insert_page(self, _workspace, hbx_tab_label, param):
        pass

    def remove_page(self, _page):
        pass

    def get_n_pages(self):
        pass
