# pylint: disable=protected-access, no-self-use, missing-docstring
# -*- coding: utf-8 -*-
#
#       tests.__mocks__.py is part of The RAMSTK Project
#
# All rights reserved.
# Copyright 2020 Doyle Rowland doyle.rowland <AT> reliaqual <DOT> com
"""File for organizing mock structures."""

# Standard Library Imports
from datetime import date, timedelta

# Third Party Imports
from treelib import Tree

MOCK_217F = {
    1: {
        'A1': 0.0,
        'A2': 0.0,
        'B1': 0.0,
        'B2': 0.0,
        'C1': 0.0,
        'C2': 0.0,
        'lambdaBD': 0.0,
        'lambdaBP': 0.0,
        'lambdaCYC': 0.0,
        'lambdaEOS': 0.0,
        'piA': 0.0,
        'piC': 0.0,
        'piCD': 0.0,
        'piCF': 0.0,
        'piCR': 0.0,
        'piCV': 0.0,
        'piCYC': 0.0,
        'piE': 0.0,
        'piF': 0.0,
        'piI': 0.0,
        'piK': 0.0,
        'piL': 0.0,
        'piM': 0.0,
        'piMFG': 0.0,
        'piN': 0.0,
        'piNR': 0.0,
        'piP': 0.0,
        'piPT': 0.0,
        'piQ': 0.0,
        'piR': 0.0,
        'piS': 0.0,
        'piT': 0.0,
        'piTAPS': 0.0,
        'piU': 0.0,
        'piV': 0.0
    },
    2: {
        'A1': 0.0,
        'A2': 0.0,
        'B1': 0.0,
        'B2': 0.0,
        'C1': 0.0,
        'C2': 0.0,
        'lambdaBD': 0.0,
        'lambdaBP': 0.0,
        'lambdaCYC': 0.0,
        'lambdaEOS': 0.0,
        'piA': 0.0,
        'piC': 0.0,
        'piCD': 0.0,
        'piCF': 0.0,
        'piCR': 0.0,
        'piCV': 0.0,
        'piCYC': 0.0,
        'piE': 0.0,
        'piF': 0.0,
        'piI': 0.0,
        'piK': 0.0,
        'piL': 0.0,
        'piM': 0.0,
        'piMFG': 0.0,
        'piN': 0.0,
        'piNR': 0.0,
        'piP': 0.0,
        'piPT': 0.0,
        'piQ': 0.0,
        'piR': 0.0,
        'piS': 0.0,
        'piT': 0.0,
        'piTAPS': 0.0,
        'piU': 0.0,
        'piV': 0.0
    }
}

MOCK_ALLOCATION = {
    1: {
        'availability_alloc': 0.0,
        'env_factor': 1,
        'goal_measure_id': 1,
        'hazard_rate_alloc': 0.0,
        'hazard_rate_goal': 0.0,
        'included': 1,
        'int_factor': 1,
        'allocation_method_id': 1,
        'mtbf_alloc': 0.0,
        'mtbf_goal': 0.0,
        'n_sub_systems': 1,
        'n_sub_elements': 1,
        'percent_weight_factor': 0.0,
        'reliability_alloc': 1.0,
        'op_time_factor': 1,
        'soa_factor': 1,
        'weight_factor': 1
    },
    2: {
        'availability_alloc': 0.0,
        'env_factor': 1,
        'goal_measure_id': 1,
        'hazard_rate_alloc': 0.0,
        'hazard_rate_goal': 0.0,
        'included': 1,
        'int_factor': 1,
        'allocation_method_id': 1,
        'mtbf_alloc': 0.0,
        'mtbf_goal': 0.0,
        'n_sub_systems': 1,
        'n_sub_elements': 1,
        'percent_weight_factor': 0.0,
        'reliability_alloc': 1.0,
        'op_time_factor': 1,
        'soa_factor': 1,
        'weight_factor': 1
    }
}

MOCK_DESIGN_ELECTRIC = {
    1: {
        'application_id': 0,
        'area': 0.0,
        'capacitance': 0.0,
        'configuration_id': 0,
        'construction_id': 0,
        'contact_form_id': 0,
        'contact_gauge': 0,
        'contact_rating_id': 0,
        'current_operating': 0.0,
        'current_rated': 0.0,
        'current_ratio': 0.0,
        'environment_active_id': 0,
        'environment_dormant_id': 0,
        'family_id': 0,
        'feature_size': 0.0,
        'frequency_operating': 0.0,
        'insert_id': 0,
        'insulation_id': 0,
        'manufacturing_id': 0,
        'matching_id': 0,
        'n_active_pins': 0,
        'n_circuit_planes': 1,
        'n_cycles': 0,
        'n_elements': 0,
        'n_hand_soldered': 0,
        'n_wave_soldered': 0,
        'operating_life': 0.0,
        'overstress': 0,
        'package_id': 0,
        'power_operating': 0.0,
        'power_rated': 0.0,
        'power_ratio': 0.0,
        'reason': '',
        'resistance': 0.0,
        'specification_id': 0,
        'technology_id': 0,
        'temperature_active': 35.0,
        'temperature_case': 0.0,
        'temperature_dormant': 25.0,
        'temperature_hot_spot': 0.0,
        'temperature_junction': 0.0,
        'temperature_knee': 25.0,
        'temperature_rated_max': 0.0,
        'temperature_rated_min': 0.0,
        'temperature_rise': 0.0,
        'theta_jc': 0.0,
        'type_id': 0,
        'voltage_ac_operating': 0.0,
        'voltage_dc_operating': 0.0,
        'voltage_esd': 0.0,
        'voltage_rated': 0.0,
        'voltage_ratio': 0.0,
        'weight': 0.0,
        'years_in_production': 1
    },
    2: {
        'application_id': 0,
        'area': 0.0,
        'capacitance': 0.0,
        'configuration_id': 0,
        'construction_id': 0,
        'contact_form_id': 0,
        'contact_gauge': 0,
        'contact_rating_id': 0,
        'current_operating': 0.0,
        'current_rated': 0.0,
        'current_ratio': 0.0,
        'environment_active_id': 0,
        'environment_dormant_id': 0,
        'family_id': 0,
        'feature_size': 0.0,
        'frequency_operating': 0.0,
        'insert_id': 0,
        'insulation_id': 0,
        'manufacturing_id': 0,
        'matching_id': 0,
        'n_active_pins': 0,
        'n_circuit_planes': 1,
        'n_cycles': 0,
        'n_elements': 0,
        'n_hand_soldered': 0,
        'n_wave_soldered': 0,
        'operating_life': 0.0,
        'overstress': 0,
        'package_id': 0,
        'power_operating': 0.0,
        'power_rated': 0.0,
        'power_ratio': 0.0,
        'reason': '',
        'resistance': 0.0,
        'specification_id': 0,
        'technology_id': 0,
        'temperature_active': 35.0,
        'temperature_case': 0.0,
        'temperature_dormant': 25.0,
        'temperature_hot_spot': 0.0,
        'temperature_junction': 0.0,
        'temperature_knee': 25.0,
        'temperature_rated_max': 0.0,
        'temperature_rated_min': 0.0,
        'temperature_rise': 0.0,
        'theta_jc': 0.0,
        'type_id': 0,
        'voltage_ac_operating': 0.0,
        'voltage_dc_operating': 0.0,
        'voltage_esd': 0.0,
        'voltage_rated': 0.0,
        'voltage_ratio': 0.0,
        'weight': 0.0,
        'years_in_production': 1
    }
}

MOCK_DESIGN_MECHANIC = {
    1: {
        'altitude_operating': 0.0,
        'application_id': 0,
        'balance_id': 0,
        'clearance': 0.0,
        'casing_id': 0,
        'contact_pressure': 0.0,
        'deflection': 0.0,
        'diameter_coil': 0.0,
        'diameter_inner': 0.0,
        'diameter_outer': 0.0,
        'diameter_wire': 0.0,
        'filter_size': 0.0,
        'flow_design': 0.0,
        'flow_operating': 0.0,
        'friction': 0.0,
        'impact_id': 0,
        'leakage_allowable': 0.0,
        'length': 0.0,
        'length_compressed': 0.0,
        'length_relaxed': 0.0,
        'load_design': 0.0,
        'load_id': 0,
        'load_operating': 0.0,
        'lubrication_id': 0,
        'material_id': 0,
        'meyer_hardness': 0.0,
        'misalignment_angle': 0.0,
        'n_ten': 0,
        'offset': 0.0,
        'particle_size': 0.0,
        'pressure_contact': 0.0,
        'pressure_delta': 0.0,
        'pressure_downstream': 0.0,
        'pressure_rated': 0.0,
        'pressure_upstream': 0.0,
        'rpm_design': 0.0,
        'rpm_operating': 0.0,
        'service_id': 0,
        'spring_index': 0.0,
        'surface_finish': 0.0,
        'thickness': 0.0,
        'torque_id': 0,
        'type_id': 0,
        'viscosity_design': 0.0,
        'viscosity_dynamic': 0.0,
        'water_per_cent': 0.0,
        'width_minimum': 0.0
    },
    2: {
        'altitude_operating': 0.0,
        'application_id': 0,
        'balance_id': 0,
        'clearance': 0.0,
        'casing_id': 0,
        'contact_pressure': 0.0,
        'deflection': 0.0,
        'diameter_coil': 0.0,
        'diameter_inner': 0.0,
        'diameter_outer': 0.0,
        'diameter_wire': 0.0,
        'filter_size': 0.0,
        'flow_design': 0.0,
        'flow_operating': 0.0,
        'friction': 0.0,
        'impact_id': 0,
        'leakage_allowable': 0.0,
        'length': 0.0,
        'length_compressed': 0.0,
        'length_relaxed': 0.0,
        'load_design': 0.0,
        'load_id': 0,
        'load_operating': 0.0,
        'lubrication_id': 0,
        'material_id': 0,
        'meyer_hardness': 0.0,
        'misalignment_angle': 0.0,
        'n_ten': 0,
        'offset': 0.0,
        'particle_size': 0.0,
        'pressure_contact': 0.0,
        'pressure_delta': 0.0,
        'pressure_downstream': 0.0,
        'pressure_rated': 0.0,
        'pressure_upstream': 0.0,
        'rpm_design': 0.0,
        'rpm_operating': 0.0,
        'service_id': 0,
        'spring_index': 0.0,
        'surface_finish': 0.0,
        'thickness': 0.0,
        'torque_id': 0,
        'type_id': 0,
        'viscosity_design': 0.0,
        'viscosity_dynamic': 0.0,
        'water_per_cent': 0.0,
        'width_minimum': 0.0
    }
}

MOCK_ENVIRONMENTS = {
    1: {
        'name': 'Condition Name',
        'units': 'Units',
        'minimum': 0.0,
        'maximum': 0.0,
        'mean': 0.0,
        'variance': 0.0,
        'ramp_rate': 0.0,
        'low_dwell_time': 0.0,
        'high_dwell_time': 0.0
    },
    2: {
        'name': 'Condition Name',
        'units': 'Units',
        'minimum': 0.0,
        'maximum': 0.0,
        'mean': 0.0,
        'variance': 0.0,
        'ramp_rate': 0.0,
        'low_dwell_time': 0.0,
        'high_dwell_time': 0.0
    },
    3: {
        'name': 'Condition Name',
        'units': 'Units',
        'minimum': 0.0,
        'maximum': 0.0,
        'mean': 0.0,
        'variance': 0.0,
        'ramp_rate': 0.0,
        'low_dwell_time': 0.0,
        'high_dwell_time': 0.0
    }
}

MOCK_FAILURE_DEFINITIONS = {1: {'definition': 'Failure Definition'}}

MOCK_FUNCTIONS = {
    1: {
        'availability_logistics': 1.0,
        'availability_mission': 1.0,
        'cost': 0.0,
        'function_code': 'PRESS-001',
        'hazard_rate_logistics': 0.0,
        'hazard_rate_mission': 0.0,
        'level': 0,
        'mcmt': 0.0,
        'mmt': 0.0,
        'mpmt': 0.0,
        'mtbf_logistics': 0.0,
        'mtbf_mission': 0.0,
        'mttr': 0.0,
        'name': 'Function Name',
        'parent_id': 0,
        'remarks': '',
        'safety_critical': 0,
        'total_mode_count': 0,
        'total_part_count': 0,
        'type_id': 0
    },
    2: {
        'availability_logistics': 1.0,
        'availability_mission': 1.0,
        'cost': 0.0,
        'function_code': 'PRESS-001',
        'hazard_rate_logistics': 0.0,
        'hazard_rate_mission': 0.0,
        'level': 0,
        'mcmt': 0.0,
        'mmt': 0.0,
        'mpmt': 0.0,
        'mtbf_logistics': 0.0,
        'mtbf_mission': 0.0,
        'mttr': 0.0,
        'name': 'Function Name',
        'parent_id': 0,
        'remarks': '',
        'safety_critical': 0,
        'total_mode_count': 0,
        'total_part_count': 0,
        'type_id': 0
    }
}

MOCK_HARDWARE = {
    1: {
        'alt_part_number': '',
        'attachments': '',
        'cage_code': '',
        'category_id': 0,
        'comp_ref_des': 'S1',
        'cost': 0.0,
        'cost_failure': 0.0,
        'cost_hour': 0.0,
        'cost_type_id': 0,
        'description': 'Test System',
        'duty_cycle': 100.0,
        'figure_number': '',
        'lcn': '',
        'level': 0,
        'manufacturer_id': 0,
        'mission_time': 100.0,
        'name': '',
        'nsn': '',
        'page_number': '',
        'parent_id': 0,
        'part': 0,
        'part_number': '',
        'quantity': 1,
        'ref_des': 'S1',
        'remarks': '',
        'repairable': 0,
        'specification_number': '',
        'subcategory_id': 0,
        'tagged_part': 0,
        'total_cost': 0.0,
        'total_part_count': 0,
        'total_power_dissipation': 0.0,
        'year_of_manufacture': 2019
    },
    2: {
        'alt_part_number': '',
        'attachments': '',
        'cage_code': '',
        'category_id': 0,
        'comp_ref_des': 'S1:SS1',
        'cost': 0.0,
        'cost_failure': 0.0,
        'cost_hour': 0.0,
        'cost_type_id': 0,
        'description': 'Test Sub-System 1',
        'duty_cycle': 100.0,
        'figure_number': '',
        'lcn': '',
        'level': 0,
        'manufacturer_id': 0,
        'mission_time': 100.0,
        'name': '',
        'nsn': '',
        'page_number': '',
        'parent_id': 1,
        'part': 0,
        'part_number': '',
        'quantity': 1,
        'ref_des': 'SS1',
        'remarks': '',
        'repairable': 0,
        'specification_number': '',
        'subcategory_id': 0,
        'tagged_part': 0,
        'total_cost': 0.0,
        'total_part_count': 0,
        'total_power_dissipation': 0.0,
        'year_of_manufacture': 2019
    }
}

MOCK_HAZARDS = {
    1: {
        'assembly_effect': '',
        'assembly_hri': 20,
        'assembly_hri_f': 4,
        'assembly_mitigation': '',
        'assembly_probability': 'Level A - Frequent',
        'assembly_probability_f': 'Level A - Frequent',
        'assembly_severity': 'Medium',
        'assembly_severity_f': 'Medium',
        'function_1': '',
        'function_2': '',
        'function_3': '',
        'function_4': '',
        'function_5': '',
        'potential_cause': '',
        'potential_hazard': '',
        'remarks': '',
        'result_1': 0.0,
        'result_2': 0.0,
        'result_3': 0.0,
        'result_4': 0.0,
        'result_5': 0.0,
        'system_effect': '',
        'system_hri': 20,
        'system_hri_f': 20,
        'system_mitigation': '',
        'system_probability': 'Level A - Frequent',
        'system_probability_f': 'Level A - Frequent',
        'system_severity': 'Medium',
        'system_severity_f': 'Medium',
        'user_blob_1': '',
        'user_blob_2': '',
        'user_blob_3': '',
        'user_float_1': 0.0,
        'user_float_2': 0.0,
        'user_float_3': 0.0,
        'user_int_1': 0,
        'user_int_2': 0,
        'user_int_3': 0
    }
}

MOCK_MISSIONS = {
    1: {
        'description': '',
        'mission_time': 0.0,
        'time_units': 'hours'
    },
    2: {
        'description': 'Mission #2',
        'mission_time': 0.0,
        'time_units': 'hours'
    }
}

MOCK_MISSION_PHASES = {
    1: {
        'description': '',
        'name': '',
        'phase_start': 0.0,
        'phase_end': 0.0
    },
    2: {
        'description': 'Phase #1 for mission #2',
        'name': '',
        'phase_start': 0.0,
        'phase_end': 0.0
    },
    3: {
        'description': 'Phase #2 for mission #2',
        'name': '',
        'phase_start': 0.0,
        'phase_end': 0.0
    }
}

MOCK_NSWC = {
    1: {
        'Cac': 0.0,
        'Calt': 0.0,
        'Cb': 0.0,
        'Cbl': 0.0,
        'Cbt': 0.0,
        'Cbv': 0.0,
        'Cc': 0.0,
        'Ccf': 0.0,
        'Ccp': 0.0,
        'Ccs': 0.0,
        'Ccv': 0.0,
        'Ccw': 0.0,
        'Cd': 0.0,
        'Cdc': 0.0,
        'Cdl': 0.0,
        'Cdp': 0.0,
        'Cds': 0.0,
        'Cdt': 0.0,
        'Cdw': 0.0,
        'Cdy': 0.0,
        'Ce': 0.0,
        'Cf': 0.0,
        'Cg': 0.0,
        'Cga': 0.0,
        'Cgl': 0.0,
        'Cgp': 0.0,
        'Cgs': 0.0,
        'Cgt': 0.0,
        'Cgv': 0.0,
        'Ch': 0.0,
        'Ci': 0.0,
        'Ck': 0.0,
        'Cl': 0.0,
        'Clc': 0.0,
        'Cm': 0.0,
        'Cmu': 0.0,
        'Cn': 0.0,
        'Cnp': 0.0,
        'Cnw': 0.0,
        'Cp': 0.0,
        'Cpd': 0.0,
        'Cpf': 0.0,
        'Cpv': 0.0,
        'Cq': 0.0,
        'Cr': 0.0,
        'Crd': 0.0,
        'Cs': 0.0,
        'Csc': 0.0,
        'Csf': 0.0,
        'Cst': 0.0,
        'Csv': 0.0,
        'Csw': 0.0,
        'Csz': 0.0,
        'Ct': 0.0,
        'Cv': 0.0,
        'Cw': 0.0,
        'Cy': 0.0
    },
    2: {
        'Cac': 0.0,
        'Calt': 0.0,
        'Cb': 0.0,
        'Cbl': 0.0,
        'Cbt': 0.0,
        'Cbv': 0.0,
        'Cc': 0.0,
        'Ccf': 0.0,
        'Ccp': 0.0,
        'Ccs': 0.0,
        'Ccv': 0.0,
        'Ccw': 0.0,
        'Cd': 0.0,
        'Cdc': 0.0,
        'Cdl': 0.0,
        'Cdp': 0.0,
        'Cds': 0.0,
        'Cdt': 0.0,
        'Cdw': 0.0,
        'Cdy': 0.0,
        'Ce': 0.0,
        'Cf': 0.0,
        'Cg': 0.0,
        'Cga': 0.0,
        'Cgl': 0.0,
        'Cgp': 0.0,
        'Cgs': 0.0,
        'Cgt': 0.0,
        'Cgv': 0.0,
        'Ch': 0.0,
        'Ci': 0.0,
        'Ck': 0.0,
        'Cl': 0.0,
        'Clc': 0.0,
        'Cm': 0.0,
        'Cmu': 0.0,
        'Cn': 0.0,
        'Cnp': 0.0,
        'Cnw': 0.0,
        'Cp': 0.0,
        'Cpd': 0.0,
        'Cpf': 0.0,
        'Cpv': 0.0,
        'Cq': 0.0,
        'Cr': 0.0,
        'Crd': 0.0,
        'Cs': 0.0,
        'Csc': 0.0,
        'Csf': 0.0,
        'Cst': 0.0,
        'Csv': 0.0,
        'Csw': 0.0,
        'Csz': 0.0,
        'Ct': 0.0,
        'Cv': 0.0,
        'Cw': 0.0,
        'Cy': 0.0
    }
}

MOCK_RELIABILITY = {
    1: {
        'add_adj_factor': 0.0,
        'availability_logistics': 1.0,
        'availability_mission': 1.0,
        'avail_log_variance': 0.0,
        'avail_mis_variance': 0.0,
        'failure_distribution_id': 0,
        'hazard_rate_active': 0.0,
        'hazard_rate_dormant': 0.0,
        'hazard_rate_logistics': 0.0,
        'hazard_rate_method_id': 0,
        'hazard_rate_mission': 0.0,
        'hazard_rate_model': '',
        'hazard_rate_percent': 0.0,
        'hazard_rate_software': 0.0,
        'hazard_rate_specified': 0.0,
        'hazard_rate_type_id': 0,
        'hr_active_variance': 0.0,
        'hr_dormant_variance': 0.0,
        'hr_logistics_variance': 0.0,
        'hr_mission_variance': 0.0,
        'hr_specified_variance': 0.0,
        'lambda_b': 0.0,
        'location_parameter': 0.0,
        'mtbf_logistics': 0.0,
        'mtbf_mission': 0.0,
        'mtbf_specified': 0.0,
        'mtbf_logistics_variance': 0.0,
        'mtbf_mission_variance': 0.0,
        'mtbf_specified_variance': 0.0,
        'mult_adj_factor': 1.0,
        'quality_id': 0,
        'reliability_goal': 1.0,
        'reliability_goal_measure_id': 0,
        'reliability_logistics': 1.0,
        'reliability_mission': 1.0,
        'reliability_log_variance': 0.0,
        'reliability_miss_variance': 0.0,
        'scale_parameter': 0.0,
        'shape_parameter': 0.0,
        'survival_analysis_id': 0
    },
    2: {
        'add_adj_factor': 0.0,
        'availability_logistics': 1.0,
        'availability_mission': 1.0,
        'avail_log_variance': 0.0,
        'avail_mis_variance': 0.0,
        'failure_distribution_id': 0,
        'hazard_rate_active': 0.0,
        'hazard_rate_dormant': 0.0,
        'hazard_rate_logistics': 0.0,
        'hazard_rate_method_id': 0,
        'hazard_rate_mission': 0.0,
        'hazard_rate_model': '',
        'hazard_rate_percent': 0.0,
        'hazard_rate_software': 0.0,
        'hazard_rate_specified': 0.0,
        'hazard_rate_type_id': 0,
        'hr_active_variance': 0.0,
        'hr_dormant_variance': 0.0,
        'hr_logistics_variance': 0.0,
        'hr_mission_variance': 0.0,
        'hr_specified_variance': 0.0,
        'lambda_b': 0.0,
        'location_parameter': 0.0,
        'mtbf_logistics': 0.0,
        'mtbf_mission': 0.0,
        'mtbf_specified': 0.0,
        'mtbf_logistics_variance': 0.0,
        'mtbf_mission_variance': 0.0,
        'mtbf_specified_variance': 0.0,
        'mult_adj_factor': 1.0,
        'quality_id': 0,
        'reliability_goal': 1.0,
        'reliability_goal_measure_id': 0,
        'reliability_logistics': 1.0,
        'reliability_mission': 1.0,
        'reliability_log_variance': 0.0,
        'reliability_miss_variance': 0.0,
        'scale_parameter': 0.0,
        'shape_parameter': 0.0,
        'survival_analysis_id': 0
    }
}

MOCK_REVISIONS = {
    1: {
        'availability_logistics': 0.9986,
        'availability_mission': 0.99934,
        'cost': 12532.15,
        'cost_failure': 0.0000352,
        'cost_hour': 1.2532,
        'hazard_rate_active': 0.0,
        'hazard_rate_dormant': 0.0,
        'hazard_rate_logistics': 0.0,
        'hazard_rate_mission': 0.0,
        'hazard_rate_software': 0.0,
        'mmt': 0.0,
        'mcmt': 0.0,
        'mpmt': 0.0,
        'mtbf_logistics': 0.0,
        'mtbf_mission': 0.0,
        'mttr': 0.0,
        'name': 'Original Revision',
        'reliability_logistics': 0.99986,
        'reliability_mission': 0.99992,
        'remarks': 'This is the original revision.',
        'revision_code': 'Rev. -',
        'program_time': 2562,
        'program_time_sd': 26.83,
        'program_cost': 26492.83,
        'program_cost_sd': 15.62
    },
    2: {
        'availability_logistics': 1.0,
        'availability_mission': 1.0,
        'cost': 0.0,
        'cost_failure': 0.0,
        'cost_hour': 0.0,
        'hazard_rate_active': 0.0,
        'hazard_rate_dormant': 0.0,
        'hazard_rate_logistics': 0.0,
        'hazard_rate_mission': 0.0,
        'hazard_rate_software': 0.0,
        'mmt': 0.0,
        'mcmt': 0.0,
        'mpmt': 0.0,
        'mtbf_logistics': 0.0,
        'mtbf_mission': 0.0,
        'mttr': 0.0,
        'name': 'Revision A',
        'reliability_logistics': 1.0,
        'reliability_mission': 1.0,
        'remarks': 'This is the second revision.',
        'revision_code': 'Rev. A',
        'program_time': 0,
        'program_time_sd': 0.0,
        'program_cost': 0.0,
        'program_cost_sd': 0.0
    }
}

MOCK_SIMILAR_ITEM = {
    1: {
        'change_description_1': '',
        'change_description_2': '',
        'change_description_3': '',
        'change_description_4': '',
        'change_description_5': '',
        'change_description_6': '',
        'change_description_7': '',
        'change_description_8': '',
        'change_description_9': '',
        'change_description_10': '',
        'change_factor_1': 1.0,
        'change_factor_2': 1.0,
        'change_factor_3': 1.0,
        'change_factor_4': 1.0,
        'change_factor_5': 1.0,
        'change_factor_6': 1.0,
        'change_factor_7': 1.0,
        'change_factor_8': 1.0,
        'change_factor_9': 1.0,
        'change_factor_10': 1.0,
        'environment_from_id': 0,
        'environment_to_id': 0,
        'function_1': '0',
        'function_2': '0',
        'function_3': '0',
        'function_4': '0',
        'function_5': '0',
        'similar_item_method_id': 1,
        'quality_from_id': 0,
        'quality_to_id': 0,
        'result_1': 0.0,
        'result_2': 0.0,
        'result_3': 0.0,
        'result_4': 0.0,
        'result_5': 0.0,
        'temperature_from': 30.0,
        'temperature_to': 30.0,
        'user_blob_1': '',
        'user_blob_2': '',
        'user_blob_3': '',
        'user_blob_4': '',
        'user_blob_5': '',
        'user_float_1': 0.0,
        'user_float_2': 0.0,
        'user_float_3': 0.0,
        'user_float_4': 0.0,
        'user_float_5': 0.0,
        'user_int_1': 0,
        'user_int_2': 0,
        'user_int_3': 0,
        'user_int_4': 0,
        'user_int_5': 0
    },
    2: {
        'change_description_1': '',
        'change_description_2': '',
        'change_description_3': '',
        'change_description_4': '',
        'change_description_5': '',
        'change_description_6': '',
        'change_description_7': '',
        'change_description_8': '',
        'change_description_9': '',
        'change_description_10': '',
        'change_factor_1': 1.0,
        'change_factor_2': 1.0,
        'change_factor_3': 1.0,
        'change_factor_4': 1.0,
        'change_factor_5': 1.0,
        'change_factor_6': 1.0,
        'change_factor_7': 1.0,
        'change_factor_8': 1.0,
        'change_factor_9': 1.0,
        'change_factor_10': 1.0,
        'environment_from_id': 0,
        'environment_to_id': 0,
        'function_1': '0',
        'function_2': '0',
        'function_3': '0',
        'function_4': '0',
        'function_5': '0',
        'similar_item_method_id': 1,
        'quality_from_id': 0,
        'quality_to_id': 0,
        'result_1': 0.0,
        'result_2': 0.0,
        'result_3': 0.0,
        'result_4': 0.0,
        'result_5': 0.0,
        'temperature_from': 30.0,
        'temperature_to': 30.0,
        'user_blob_1': '',
        'user_blob_2': '',
        'user_blob_3': '',
        'user_blob_4': '',
        'user_blob_5': '',
        'user_float_1': 0.0,
        'user_float_2': 0.0,
        'user_float_3': 0.0,
        'user_float_4': 0.0,
        'user_float_5': 0.0,
        'user_int_1': 0,
        'user_int_2': 0,
        'user_int_3': 0,
        'user_int_4': 0,
        'user_int_5': 0
    }
}

MOCK_STATUS = {
    1: {
        'cost_remaining': 284.98,
        'date_status': date.today() - timedelta(days=1),
        'time_remaining': 125.0
    },
    2: {
        'cost_remaining': 212.32,
        'date_status': date.today(),
        'time_remaining': 112.5
    }
}

MOCK_REQUIREMENTS = {
    1: {
        'derived': 0,
        'description': '',
        'figure_number': '',
        'owner': '',
        'page_number': '',
        'parent_id': 0,
        'priority': 0,
        'requirement_code': 'REL.1',
        'specification': '',
        'requirement_type': '',
        'validated': 0,
        'validated_date': date.today(),
        'q_clarity_0': 0,
        'q_clarity_1': 0,
        'q_clarity_2': 0,
        'q_clarity_3': 0,
        'q_clarity_4': 0,
        'q_clarity_5': 0,
        'q_clarity_6': 0,
        'q_clarity_7': 0,
        'q_clarity_8': 0,
        'q_complete_0': 0,
        'q_complete_1': 0,
        'q_complete_2': 0,
        'q_complete_3': 0,
        'q_complete_4': 0,
        'q_complete_5': 0,
        'q_complete_6': 0,
        'q_complete_7': 0,
        'q_complete_8': 0,
        'q_complete_9': 0,
        'q_consistent_0': 0,
        'q_consistent_1': 0,
        'q_consistent_2': 0,
        'q_consistent_3': 0,
        'q_consistent_4': 0,
        'q_consistent_5': 0,
        'q_consistent_6': 0,
        'q_consistent_7': 0,
        'q_consistent_8': 0,
        'q_verifiable_0': 0,
        'q_verifiable_1': 0,
        'q_verifiable_2': 0,
        'q_verifiable_3': 0,
        'q_verifiable_4': 0,
        'q_verifiable_5': 0
    },
    2: {
        'derived': 1,
        'description': 'Derived requirement #1 for base requirement #1.',
        'figure_number': '',
        'owner': '',
        'page_number': '',
        'parent_id': 1,
        'priority': 0,
        'requirement_code': 'REL.1.1',
        'specification': '',
        'requirement_type': '',
        'validated': 0,
        'validated_date': date.today(),
        'q_clarity_0': 0,
        'q_clarity_1': 0,
        'q_clarity_2': 0,
        'q_clarity_3': 0,
        'q_clarity_4': 0,
        'q_clarity_5': 0,
        'q_clarity_6': 0,
        'q_clarity_7': 0,
        'q_clarity_8': 0,
        'q_complete_0': 0,
        'q_complete_1': 0,
        'q_complete_2': 0,
        'q_complete_3': 0,
        'q_complete_4': 0,
        'q_complete_5': 0,
        'q_complete_6': 0,
        'q_complete_7': 0,
        'q_complete_8': 0,
        'q_complete_9': 0,
        'q_consistent_0': 0,
        'q_consistent_1': 0,
        'q_consistent_2': 0,
        'q_consistent_3': 0,
        'q_consistent_4': 0,
        'q_consistent_5': 0,
        'q_consistent_6': 0,
        'q_consistent_7': 0,
        'q_consistent_8': 0,
        'q_verifiable_0': 0,
        'q_verifiable_1': 0,
        'q_verifiable_2': 0,
        'q_verifiable_3': 0,
        'q_verifiable_4': 0,
        'q_verifiable_5': 0
    }
}

MOCK_STAKEHOLDERS = {
    1: {
        'customer_rank': 1,
        'description': 'Stakeholder Input',
        'group': '',
        'improvement': 0.0,
        'overall_weight': 0.0,
        'planned_rank': 1,
        'priority': 1,
        'requirement_id': 0,
        'stakeholder': '',
        'user_float_1': 1.0,
        'user_float_2': 1.0,
        'user_float_3': 1.0,
        'user_float_4': 1.0,
        'user_float_5': 1.0
    },
    2: {
        'customer_rank': 1,
        'description': 'Stakeholder Input',
        'group': '',
        'improvement': 0.0,
        'overall_weight': 0.0,
        'planned_rank': 1,
        'priority': 1,
        'requirement_id': 0,
        'stakeholder': '',
        'user_float_1': 1.0,
        'user_float_2': 1.0,
        'user_float_3': 1.0,
        'user_float_4': 1.0,
        'user_float_5': 1.0
    }
}

MOCK_VALIDATIONS = {
    1: {
        'acceptable_maximum': 30.0,
        'acceptable_mean': 20.0,
        'acceptable_minimum': 10.0,
        'acceptable_variance': 0.0,
        'confidence': 95.0,
        'cost_average': 0.0,
        'cost_ll': 0.0,
        'cost_maximum': 0.0,
        'cost_mean': 0.0,
        'cost_minimum': 0.0,
        'cost_ul': 0.0,
        'cost_variance': 0.0,
        'date_end': date.today() + timedelta(days=30),
        'date_start': date.today(),
        'description': '',
        'measurement_unit': '',
        'name': 'PRF-0001',
        'status': 0.0,
        'task_type': '',
        'task_specification': '',
        'time_average': 0.0,
        'time_ll': 0.0,
        'time_maximum': 0.0,
        'time_mean': 0.0,
        'time_minimum': 0.0,
        'time_ul': 0.0,
        'time_variance': 0.0
    },
    2: {
        'acceptable_maximum': 30.0,
        'acceptable_mean': 20.0,
        'acceptable_minimum': 10.0,
        'acceptable_variance': 0.0,
        'confidence': 95.0,
        'cost_average': 0.0,
        'cost_ll': 0.0,
        'cost_maximum': 0.0,
        'cost_mean': 0.0,
        'cost_minimum': 0.0,
        'cost_ul': 0.0,
        'cost_variance': 0.0,
        'date_end': date.today() + timedelta(days=20),
        'date_start': date.today() - timedelta(days=10),
        'description': '',
        'measurement_unit': '',
        'name': '',
        'status': 0.0,
        'task_type': 'Reliability, Assessment',
        'task_specification': '',
        'time_average': 0.0,
        'time_ll': 0.0,
        'time_maximum': 0.0,
        'time_mean': 0.0,
        'time_minimum': 0.0,
        'time_ul': 0.0,
        'time_variance': 0.0
    },
    3: {
        'acceptable_maximum': 30.0,
        'acceptable_mean': 20.0,
        'acceptable_minimum': 10.0,
        'acceptable_variance': 0.0,
        'confidence': 95.0,
        'cost_average': 0.0,
        'cost_ll': 0.0,
        'cost_maximum': 0.0,
        'cost_mean': 0.0,
        'cost_minimum': 0.0,
        'cost_ul': 0.0,
        'cost_variance': 0.0,
        'date_end': date.today() + timedelta(days=30),
        'date_start': date.today(),
        'description': '',
        'measurement_unit': '',
        'name': '',
        'status': 0.0,
        'task_type': 'Reliability, Assessment',
        'task_specification': '',
        'time_average': 20.0,
        'time_ll': 19.0,
        'time_maximum': 40.0,
        'time_mean': 34.0,
        'time_minimum': 12.0,
        'time_ul': 49.0,
        'time_variance': 0.0
    }
}

# Mock treelib Tree()'s.
MOCK_FNCTN_TREE = Tree()
MOCK_FNCTN_TREE.create_node(tag='function',
                            identifier=0,
                            parent=None,
                            data=None)

MOCK_HRDWR_TREE = Tree()
MOCK_HRDWR_TREE.create_node(tag='hardware',
                            identifier=0,
                            parent=None,
                            data=None)
MOCK_HRDWR_TREE.create_node(tag='S1', identifier=1, parent=0, data=None)
MOCK_HRDWR_TREE.create_node(tag='S1:SS1', identifier=2, parent=1, data=None)
MOCK_HRDWR_TREE.create_node(tag='S1:SS2', identifier=3, parent=1, data=None)
MOCK_HRDWR_TREE.create_node(tag='S1:SS3', identifier=4, parent=1, data=None)
MOCK_HRDWR_TREE.create_node(tag='S1:SS4', identifier=5, parent=1, data=None)
MOCK_HRDWR_TREE.create_node(tag='S1:SS1:A1', identifier=6, parent=5, data=None)
MOCK_HRDWR_TREE.create_node(tag='S1:SS1:A2', identifier=7, parent=5, data=None)
MOCK_HRDWR_TREE.create_node(tag='S1:SS1:A2:C1',
                            identifier=8,
                            parent=7,
                            data=None)

MOCK_RQRMNT_TREE = Tree()
MOCK_RQRMNT_TREE.create_node(tag='requirement',
                             identifier=0,
                             parent=None,
                             data=None)
MOCK_RQRMNT_TREE.create_node(tag='REL-0001', identifier=1, parent=0, data=None)
MOCK_RQRMNT_TREE.create_node(tag='PRF-0002', identifier=2, parent=0, data=None)
MOCK_RQRMNT_TREE.create_node(tag='FUN-0003', identifier=3, parent=0, data=None)
