# Stubs for ramstk.views.gtk3.revision.listview (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.


class RAMSTKBaseView(Gtk.HBox):
    def __init__(self) -> None:
        self._on_button_press = None
        self._on_row_change = None
        ...

    def _do_request_insert(self, sibling, param):
        pass

    def get_parent(self):
        pass

    def on_button_press(self, event: Gdk.Event, **kwargs: Any):
        pass

    def get_parent_window(self):
        pass

class RAMSTKListView(RAMSTKBaseView):


class RAMSTKModuleView(RAMSTKBaseView):


class RAMSTKWorkView(RAMSTKBaseView):
