# Stubs for ramstk.views.gtk3.widgets.button (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ramstk.views.gtk3 import Gtk
from typing import Any, Tuple

def do_set_common_properties(**kwargs: Any) -> Tuple[int, str, int]: ...
def do_make_buttonbox(view: Any, **kwargs: Any) -> Gtk.ButtonBox: ...

class RAMSTKButton(Gtk.Button):
    def __init__(self, label: str=..., **kwargs: Any) -> None: ...
    def do_set_properties(self, **kwargs: Any) -> None: ...

    def set_property(self, param, _height):
        pass

    def set_image(self, _image):
        pass

    def show_all(self):
        pass


class RAMSTKCheckButton(Gtk.CheckButton):
    def __init__(self, label: str=...) -> None: ...
    def do_set_properties(self, **kwargs: Any) -> None: ...
    def do_update(self, value: int, handler_id: int) -> None: ...

    def handler_block(self, handler_id):
        pass

    def set_active(self, param):
        pass

    def handler_unblock(self, handler_id):
        pass

    def get_child(self):
        pass

    def set_property(self, param, _tooltip):
        pass

    def connect(self, param, _on_toggled, param1):
        pass


class RAMSTKOptionButton(Gtk.RadioButton):
    def __init__(self, group: Gtk.RadioButton=..., label: str=...) -> None: ...
