# Stubs for ramstk.views.gtk3.widgets.combo (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ramstk.views.gtk3 import Gtk
from typing import Any, Dict, List

class RAMSTKComboBox(Gtk.ComboBox):
    def __init__(self, index: int=..., simple: bool=...) -> None: ...
    def do_get_options(self) -> Dict[int, Any]: ...
    def do_load_combo(self, entries: List[List[str]], simple: bool=...) -> None: ...
    def do_set_properties(self, **kwargs: Any) -> None: ...
    def do_update(self, value: str, handler_id: object) -> object: ...

    def connect(self, param, _on_combo_changed, param1):
        pass

    def handler_block(self, param):
        pass

    def set_active(self, param):
        pass

    def handler_unblock(self, param):
        pass
