# Standard Library Imports
from datetime import date

# Third Party Imports
from _typeshed import Incomplete

# RAMSTK Package Imports
from ramstk.views.gtk3 import Gtk as Gtk
from ramstk.views.gtk3 import Pango as Pango

# RAMSTK Local Imports
from .widget import RAMSTKBaseWidget as RAMSTKBaseWidget
from .widget import WidgetProperties as WidgetProperties

class RAMSTKEntry(Gtk.Entry, RAMSTKBaseWidget):
    def __init__(self) -> None: ...
    def do_set_properties(self, properties: WidgetProperties) -> None: ...
    def do_update(
        self, package: dict[str, bool | date | float | int | str]
    ) -> None: ...
    def on_changed(self, /, __entry: RAMSTKBaseWidget) -> None: ...
    def do_get_text(self) -> float | int | str | None: ...

class RAMSTKTextView(Gtk.TextView, RAMSTKBaseWidget):
    tag_bold: Incomplete
    scrollwindow: Incomplete
    def __init__(self, txtbuffer: Gtk.TextBuffer) -> None: ...
    def do_set_properties(self, properties: WidgetProperties) -> None: ...
    def do_update(
        self, package: dict[str, bool | date | float | int | str]
    ) -> None: ...
    def on_changed(self) -> None: ...
    def do_get_text(self) -> str: ...
