# Stubs for ramstk.views.gtk3.widgets.entry (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ramstk.views.gtk3 import Gtk
from typing import Any, Tuple

def do_set_common_properties(**kwargs: Any) -> Tuple[int, str, int]: ...

class RAMSTKEntry(Gtk.Entry):
    def __init__(self) -> None: ...
    def do_set_properties(self, **kwargs: Any) -> None: ...
    def do_update(self, value: str, handler_id: int) -> None: ...

    # The following methods are inherited from the Gtk.Entry() base class.
    def set_text(self, param):
        pass

    def set_tooltip_markup(self, _tooltip):
        pass

    def modify_font(self, param):
        pass

    def override_background_color(self, INSENSITIVE, param):
        pass

    def set_property(self, param, _width):
        pass

    def show(self):
        pass

    def connect(self, param, _on_focus_out, param1):
        pass


class RAMSTKTextView(Gtk.TextView):
    scrollwindow: Any = ...
    tag_bold: Any = ...
    def __init__(self, txvbuffer: Gtk.TextBuffer=...) -> None: ...
    def do_get_buffer(self) -> Gtk.TextBuffer: ...
    def do_get_text(self) -> Any: ...
    def do_set_properties(self, **kwargs: Any) -> None: ...
    def do_update(self, value: str, handler_id: int) -> None: ...

    # The following methods are inherited from the Gtk.Entry() base class.
    def set_property(self, param, _tooltip):
        pass

    def get_buffer(self):
        pass

    def set_wrap_mode(self, WORD):
        pass

    def set_buffer(self, txvbuffer):
        pass
