# Stubs for ramstk.views.gtk3.widgets.label (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ramstk.views.gtk3 import Gtk
from typing import Any, List, Tuple

def do_make_label_group(text: List[str], container: Gtk.Fixed, x_pos: int,
                        y_pos: int, **kwargs: Any) -> Tuple[int, List[int]]: ...

class RAMSTKLabel(Gtk.Label):
    def __init__(self, text: str) -> None: ...
    def get_attribute(self, attribute: str) -> Any: ...
    def do_set_properties(self, **kwargs: Any) -> None: ...

    def show(self):
        pass
