from .widget import RAMSTKWidget as RAMSTKWidget
from ramstk.views.gtk3 import Gtk as Gtk
from typing import Any, Dict, List, Tuple

class RAMSTKLabel(Gtk.Label, RAMSTKWidget):
    def __init__(self, text: str) -> None: ...
    def get_attribute(self, attribute: str) -> Any: ...
    def do_set_properties(self, **kwargs: Any) -> None: ...

def do_make_label_group(text: List[str], **kwargs: Dict[str, Any]) -> Tuple[int, List[RAMSTKLabel]]: ...
