# Stubs for ramstk.views.gtk3.widgets.panel (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

# Standard Library Imports
from typing import Any, Dict, List, Union

# RAMSTK Package Imports
from ramstk.views.gtk3 import Gdk, Gtk
from ramstk.views.gtk3.widgets import (
    RAMSTKCheckButton, RAMSTKComboBox,
    RAMSTKEntry, RAMSTKFrame, RAMSTKTreeView
)


class RAMSTKPanel(RAMSTKFrame):
    def __init__(self) -> None:
        ...

    def do_make_panel_fixed(self) -> None:
        ...

    @staticmethod
    def do_make_panel_plot(plot: object) -> Gtk.ScrolledWindow:
        ...

    @staticmethod
    def do_make_panel_treeview(treeview: RAMSTKTreeView) -> Gtk.ScrolledWindow:
        ...

    def on_changed_combo(self, combo: RAMSTKComboBox, index: int,
                         message: str) -> Dict[Union[str, Any], Any]:
        ...

    def on_changed_text(self, entry: RAMSTKEntry, index: int,
                        message: str) -> Dict[Union[str, Any], Any]:
        ...

    def on_edit(self, node_id: List[int], package: Dict[str, Any]) -> None:
        ...

    def on_focus_out(self, entry: object, __event: Gdk.EventFocus, index: int,
                     message: str) -> Dict[Union[str, Any], Any]:
        ...

    def on_toggled(self, checkbutton: RAMSTKCheckButton, index: int,
                   message: str) -> Dict[Union[str, Any], Any]:
        ...
