# RAMSTK Local Imports
from ..frame import RAMSTKFrame as RAMSTKFrame
from ..widget import WidgetConfig as WidgetConfig

def do_log_message(
    method_name: str, topic_name: str, logger_name: str, message: str
) -> None: ...

class RAMSTKBasePanel(RAMSTKFrame):
    def __init__(self) -> None: ...
    def do_set_widget_attributes(self) -> None: ...
    def do_set_widget_callbacks(self) -> None: ...
    def do_set_widget_properties(self) -> None: ...
