# Standard Library Imports
from typing import Any

# Third Party Imports
import treelib

# RAMSTK Package Imports
from ramstk.utilities import string_to_boolean as string_to_boolean
from ramstk.views.gtk3 import GdkPixbuf as GdkPixbuf
from ramstk.views.gtk3 import GObject as GObject
from ramstk.views.gtk3 import Gtk as Gtk
from ramstk.views.gtk3 import _ as _

# RAMSTK Local Imports
from ..label import RAMSTKLabel as RAMSTKLabel
from ..treeviews import RAMSTKTreeView as RAMSTKTreeView
from . import RAMSTKBasePanel as RAMSTKBasePanel
from . import do_log_message as do_log_message

def do_get_selected_row_attributes(
    selection: Gtk.TreeSelection, dic_attribute_widget_map: dict, position: dict
) -> dict: ...

class RAMSTKTreePanel(RAMSTKBasePanel):
    tvwTreeView: RAMSTKTreeView
    _filtered_tree: bool
    level: str
    def __init__(self) -> None: ...
    def do_set_widget_properties(self) -> None: ...
    def _do_subscribe_to_messages(self) -> None: ...
    def do_clear_tree_panel(self) -> None: ...
    def do_load_tree_panel(self, tree: treelib.Tree) -> None: ...
    def do_make_tree_panel(self) -> None: ...
    def do_make_treeview(self, format_file: str) -> None: ...
    def on_delete_row(self, tree: treelib.Tree) -> None: ...
    @staticmethod
    def do_set_title(title: str) -> None: ...
    def on_row_change(self, selection: Gtk.TreeSelection) -> dict[str, Any]: ...
    def do_refresh_tree(self, node_id: int, package: dict[str, Any]) -> None: ...
    def do_set_headings(self) -> None: ...
    def do_set_visible_columns(self) -> None: ...
