from ramstk.views.gtk3.widgets import RAMSTKComboBox as RAMSTKComboBox, RAMSTKEntry as RAMSTKEntry, RAMSTKLabel as RAMSTKLabel, RAMSTKPanel as RAMSTKPanel
from typing import Any

class AssessmentInputPanel(RAMSTKPanel):
    fmt: str = ...
    cmbConfiguration: Any = ...
    cmbConstruction: Any = ...
    cmbQuality: Any = ...
    cmbSpecification: Any = ...
    cmbStyle: Any = ...
    txtCapacitance: Any = ...
    txtESR: Any = ...
    def __init__(self) -> None: ...
    def do_load_comboboxes(self, subcategory_id: int) -> None: ...

class AssessmentResultsPanel(RAMSTKPanel):
    fmt: str = ...
    lblModel: Any = ...
    txtLambdaB: Any = ...
    txtPiCV: Any = ...
    txtPiCF: Any = ...
    txtPiC: Any = ...
    txtPiE: Any = ...
    txtPiQ: Any = ...
    def __init__(self) -> None: ...
