from ramstk.views.gtk3.widgets import RAMSTKComboBox as RAMSTKComboBox, RAMSTKEntry as RAMSTKEntry, RAMSTKLabel as RAMSTKLabel, RAMSTKPanel as RAMSTKPanel
from typing import Any

class AssessmentInputs(RAMSTKPanel):
    fmt: str = ...
    cmbInsert: Any = ...
    cmbQuality: Any = ...
    cmbSpecification: Any = ...
    cmbType: Any = ...
    txtContactGauge: Any = ...
    txtActivePins: Any = ...
    txtAmpsContact: Any = ...
    txtMating: Any = ...
    txtNWave: Any = ...
    txtNHand: Any = ...
    txtNPlanes: Any = ...
    def __init__(self) -> None: ...
    def do_load_comboboxes(self, subcategory_id: int) -> None: ...

class AssessmentResults(RAMSTKPanel):
    fmt: str = ...
    lblModel: Any = ...
    txtLambdaB: Any = ...
    txtPiC: Any = ...
    txtPiE: Any = ...
    txtPiK: Any = ...
    txtPiP: Any = ...
    txtPiQ: Any = ...
    def __init__(self) -> None: ...
