from ramstk.views.gtk3.widgets import RAMSTKComboBox as RAMSTKComboBox, RAMSTKEntry as RAMSTKEntry, RAMSTKLabel as RAMSTKLabel, RAMSTKPanel as RAMSTKPanel
from typing import Any

class AssessmentInputPanel(RAMSTKPanel):
    fmt: str = ...
    cmbConstruction: Any = ...
    cmbFamily: Any = ...
    cmbInsulation: Any = ...
    cmbQuality: Any = ...
    cmbSpecification: Any = ...
    txtArea: Any = ...
    txtWeight: Any = ...
    def __init__(self) -> None: ...
    def do_load_comboboxes(self, subcategory_id: int) -> None: ...

class AssessmentResultPanel(RAMSTKPanel):
    fmt: str = ...
    lblModel: Any = ...
    txtLambdaB: Any = ...
    txtPiC: Any = ...
    txtPiE: Any = ...
    txtPiQ: Any = ...
    def __init__(self) -> None: ...
