from ramstk.views.gtk3.widgets import RAMSTKComboBox as RAMSTKComboBox, RAMSTKEntry as RAMSTKEntry, RAMSTKLabel as RAMSTKLabel, RAMSTKPanel as RAMSTKPanel
from typing import Any

class AssessmentInputPanel(RAMSTKPanel):
    fmt: str = ...
    cmbApplication: Any = ...
    cmbConstruction: Any = ...
    cmbECC: Any = ...
    cmbManufacturing: Any = ...
    cmbQuality: Any = ...
    cmbPackage: Any = ...
    cmbTechnology: Any = ...
    cmbType: Any = ...
    txtArea: Any = ...
    txtFeatureSize: Any = ...
    txtNActivePins: Any = ...
    txtNCycles: Any = ...
    txtNElements: Any = ...
    txtOperatingLife: Any = ...
    txtThetaJC: Any = ...
    txtVoltageESD: Any = ...
    txtYearsInProduction: Any = ...
    def __init__(self) -> None: ...
    def do_load_comboboxes(self, subcategory_id: int) -> None: ...

class AssessmentResultPanel(RAMSTKPanel):
    fmt: str = ...
    lblModel: Any = ...
    txtC1: Any = ...
    txtC2: Any = ...
    txtLambdaB: Any = ...
    txtLambdaBD: Any = ...
    txtLambdaBP: Any = ...
    txtLambdaCYC: Any = ...
    txtLambdaEOS: Any = ...
    txtPiA: Any = ...
    txtPiCD: Any = ...
    txtPiE: Any = ...
    txtPiL: Any = ...
    txtPiMFG: Any = ...
    txtPiQ: Any = ...
    txtPiPT: Any = ...
    txtPiT: Any = ...
    def __init__(self) -> None: ...
