from ramstk.views.gtk3.widgets import RAMSTKComboBox as RAMSTKComboBox, RAMSTKEntry as RAMSTKEntry, RAMSTKLabel as RAMSTKLabel, RAMSTKPanel as RAMSTKPanel
from typing import Any

class AssessmentInputPanel(RAMSTKPanel):
    cmbApplication: Any = ...
    cmbQuality: Any = ...
    cmbType: Any = ...
    txtFrequency: Any = ...
    txtUtilization: Any = ...
    def __init__(self) -> None: ...
    def do_load_comboboxes(self, subcategory_id: int) -> None: ...

class AssessmentResultPanel(RAMSTKPanel):
    lblModel: Any = ...
    txtLambdaB: Any = ...
    txtPiA: Any = ...
    txtPiE: Any = ...
    txtPiQ: Any = ...
    txtPiU: Any = ...
    def __init__(self) -> None: ...
