# Standard Library Imports
from typing import Any, Dict

# RAMSTK Package Imports
from ramstk.views.gtk3 import _ as _
from ramstk.views.gtk3.widgets import RAMSTKComboBox as RAMSTKComboBox
from ramstk.views.gtk3.widgets import RAMSTKEntry as RAMSTKEntry

# RAMSTK Local Imports
from .panels import RAMSTKAssessmentInputPanel as RAMSTKAssessmentInputPanel
from .panels import RAMSTKAssessmentResultPanel as RAMSTKAssessmentResultPanel

class AssessmentInputPanel(RAMSTKAssessmentInputPanel):
    _dic_attribute_keys: Any = ...
    _lst_labels: Any = ...
    _lst_tooltips: Any = ...
    cmbApplication: Any = ...
    cmbType: Any = ...
    txtFrequency: Any = ...
    txtUtilization: Any = ...
    _dic_attribute_updater: Any = ...
    _lst_widgets: Any = ...

    def __init__(self) -> None:
        ...

    def do_load_comboboxes(self, subcategory_id: int) -> None:
        ...

    def _do_load_panel(self, attributes: Dict[str, Any]) -> None:
        ...

    def _do_set_sensitive(self) -> None:
        ...

    def __do_load_crystal(self, attributes: Dict[str, Any]) -> None:
        ...

    def __do_load_filter(self, attributes: Dict[str, Any]) -> None:
        ...

    def __do_load_lamp(self, attributes: Dict[str, Any]) -> None:
        ...

    def __do_set_crystal_sensitive(self) -> None:
        ...

    def __do_set_filter_sensitive(self) -> None:
        ...

    def __do_set_lamp_sensitive(self) -> None:
        ...

    def __set_callbacks(self) -> None:
        ...

    def __set_properties(self) -> None:
        ...


class AssessmentResultPanel(RAMSTKAssessmentResultPanel):
    _dic_part_stress: Any = ...
    _lst_labels: Any = ...
    _lst_tooltips: Any = ...
    txtPiA: Any = ...
    txtPiU: Any = ...
    _lst_widgets: Any = ...

    def __init__(self) -> None:
        ...

    def _do_load_panel(self, attributes: Dict[str, Any]) -> None:
        ...

    def _do_set_sensitive(self) -> None:
        ...

    def __do_set_crystal_sensitive(self) -> None:
        ...

    def __do_set_filter_sensitive(self) -> None:
        ...

    def __do_set_lamp_sensitive(self) -> None:
        ...
