# Standard Library Imports
from typing import Any, Dict

# RAMSTK Package Imports
from ramstk.views.gtk3 import Gtk as Gtk
from ramstk.views.gtk3 import _ as _
from ramstk.views.gtk3.widgets import RAMSTKCheckButton as RAMSTKCheckButton
from ramstk.views.gtk3.widgets import RAMSTKComboBox as RAMSTKComboBox
from ramstk.views.gtk3.widgets import RAMSTKEntry as RAMSTKEntry
from ramstk.views.gtk3.widgets import RAMSTKLabel as RAMSTKLabel
from ramstk.views.gtk3.widgets import RAMSTKPanel as RAMSTKPanel
from ramstk.views.gtk3.widgets import (
    RAMSTKScrolledWindow as RAMSTKScrolledWindow
)
from ramstk.views.gtk3.widgets import RAMSTKTextView as RAMSTKTextView

class RAMSTKAssessmentInputPanel(RAMSTKPanel):
    _dic_attribute_keys: Any = ...
    _lst_labels: Any = ...
    _lst_tooltips: Any = ...
    _hazard_rate_method_id: int = ...
    _subcategory_id: int = ...
    _title: Any = ...
    cmbQuality: Any = ...

    def __init__(self) -> None:
        ...

    _record_id: Any = ...

    def do_load_common(self, attributes: Dict[str, Any]) -> None:
        ...

    def do_set_properties(self, **kwargs: Dict[str, Any]) -> None:
        ...


class RAMSTKStressInputPanel(RAMSTKPanel):
    _dic_attribute_keys: Any = ...
    _lst_labels: Any = ...
    _lst_tooltips: Any = ...
    _record_id: int = ...
    _subcategory_id: int = ...
    _title: Any = ...
    txtTemperatureRatedMin: Any = ...
    txtTemperatureKnee: Any = ...
    txtTemperatureRatedMax: Any = ...
    txtCurrentRated: Any = ...
    txtCurrentOperating: Any = ...
    txtPowerRated: Any = ...
    txtPowerOperating: Any = ...
    txtVoltageRated: Any = ...
    txtVoltageAC: Any = ...
    txtVoltageDC: Any = ...
    _lst_widgets: Any = ...

    def __init__(self) -> None:
        ...

    def _do_load_panel(self, attributes: Dict[str, Any]) -> None:
        ...

    def __set_callbacks(self) -> None:
        ...

    def __set_properties(self) -> None:
        ...


class RAMSTKAssessmentResultPanel(RAMSTKPanel):
    _lst_labels: Any = ...
    _lst_tooltips: Any = ...
    _hazard_rate_method_id: int = ...
    _subcategory_id: int = ...
    _title: Any = ...
    lblModel: Any = ...
    txtLambdaB: Any = ...
    txtPiQ: Any = ...
    txtPiE: Any = ...

    def __init__(self) -> None:
        ...

    _record_id: Any = ...

    def do_load_common(self, attributes: Dict[str, Any]) -> None:
        ...

    def do_set_properties(self, **kwargs: Dict[str, Any]) -> None:
        ...

    def __do_set_model_label(self) -> None:
        ...


class RAMSTKStressResultPanel(RAMSTKPanel):
    _lst_derate_criteria: Any = ...
    _lst_labels: Any = ...
    _lst_tooltips: Any = ...
    _record_id: int = ...
    _subcategory_id: int = ...
    _title: Any = ...
    chkOverstress: Any = ...
    txtCurrentRatio: Any = ...
    txtPowerRatio: Any = ...
    txtVoltageRatio: Any = ...
    txtReason: Any = ...
    _lst_widgets: Any = ...

    def __init__(self) -> None:
        ...

    def _do_load_derating_curve(self,
                                attributes: Dict[str, Any],
                                stress: str = ...) -> None:
        ...

    def _do_load_panel(self, attributes: Dict[str, Any]) -> None:
        ...

    def __make_ui(self) -> None:
        ...

    def __set_properties(self) -> None:
        ...
