# Standard Library Imports
from typing import Any, Dict

# RAMSTK Package Imports
from ramstk.views.gtk3 import Gtk as Gtk
from ramstk.views.gtk3.widgets import RAMSTKCheckButton as RAMSTKCheckButton
from ramstk.views.gtk3.widgets import RAMSTKComboBox as RAMSTKComboBox
from ramstk.views.gtk3.widgets import RAMSTKEntry as RAMSTKEntry
from ramstk.views.gtk3.widgets import RAMSTKLabel as RAMSTKLabel
from ramstk.views.gtk3.widgets import RAMSTKPanel as RAMSTKPanel
from ramstk.views.gtk3.widgets import (
    RAMSTKScrolledWindow as RAMSTKScrolledWindow
)
from ramstk.views.gtk3.widgets import RAMSTKTextView as RAMSTKTextView

class RAMSTKAssessmentInputPanel(RAMSTKPanel):
    cmbQuality: Any = ...

    def __init__(self) -> None:
        ...

    def do_load_panel(self, attributes: Dict[str, Any]) -> None:
        ...

    def do_set_properties(self, **kwargs: Dict[str, Any]) -> None:
        ...


class RAMSTKStressInputPanel(RAMSTKPanel):
    txtTemperatureRatedMin: Any = ...
    txtTemperatureKnee: Any = ...
    txtTemperatureRatedMax: Any = ...
    txtCurrentRated: Any = ...
    txtCurrentOperating: Any = ...
    txtPowerRated: Any = ...
    txtPowerOperating: Any = ...
    txtVoltageRated: Any = ...
    txtVoltageAC: Any = ...
    txtVoltageDC: Any = ...

    def __init__(self) -> None:
        ...


class RAMSTKAssessmentResultPanel(RAMSTKPanel):
    lblModel: Any = ...
    txtLambdaB: Any = ...
    txtPiQ: Any = ...
    txtPiE: Any = ...

    def __init__(self) -> None:
        ...

    def do_load_panel(self, attributes: Dict[str, Any]) -> None:
        ...

    def do_set_properties(self, **kwargs: Dict[str, Any]) -> None:
        ...


class RAMSTKStressResultPanel(RAMSTKPanel):
    chkOverstress: Any = ...
    txtCurrentRatio: Any = ...
    txtPowerRatio: Any = ...
    txtVoltageRatio: Any = ...
    txtReason: Any = ...

    def __init__(self) -> None:
        ...
