from ramstk.views.gtk3.widgets import RAMSTKComboBox as RAMSTKComboBox, RAMSTKEntry as RAMSTKEntry, RAMSTKLabel as RAMSTKLabel, RAMSTKPanel as RAMSTKPanel
from typing import Any

class AssessmentInputPanel(RAMSTKPanel):
    cmbType: Any = ...
    cmbLoadType: Any = ...
    cmbContactForm: Any = ...
    cmbContactRating: Any = ...
    cmbApplication: Any = ...
    cmbConstruction: Any = ...
    txtCycles: Any = ...
    def __init__(self) -> None: ...
    def do_load_comboboxes(self, subcategory_id: int) -> None: ...

class AssessmentResultPanel(RAMSTKPanel):
    lblModel: Any = ...
    txtLambdaB: Any = ...
    txtPiC: Any = ...
    txtPiCYC: Any = ...
    txtPiE: Any = ...
    txtPiF: Any = ...
    txtPiL: Any = ...
    txtPiQ: Any = ...
    def __init__(self) -> None: ...
