from .panels import RAMSTKAssessmentInputPanel as RAMSTKAssessmentInputPanel, RAMSTKAssessmentResultPanel as RAMSTKAssessmentResultPanel
from ramstk.views.gtk3.widgets import RAMSTKComboBox as RAMSTKComboBox, RAMSTKEntry as RAMSTKEntry
from typing import Any

class AssessmentInputPanel(RAMSTKAssessmentInputPanel):
    cmbApplication: Any = ...
    cmbConstruction: Any = ...
    cmbContactForm: Any = ...
    cmbContactRating: Any = ...
    cmbLoadType: Any = ...
    cmbType: Any = ...
    txtCycles: Any = ...
    def __init__(self) -> None: ...
    def do_load_comboboxes(self, subcategory_id: int) -> None: ...

class AssessmentResultPanel(RAMSTKAssessmentResultPanel):
    txtPiC: Any = ...
    txtPiCYC: Any = ...
    txtPiF: Any = ...
    txtPiL: Any = ...
    def __init__(self) -> None: ...
