# Standard Library Imports
from typing import Any, Dict, List

# RAMSTK Package Imports
from ramstk.views.gtk3 import _ as _
from ramstk.views.gtk3.widgets import RAMSTKComboBox as RAMSTKComboBox
from ramstk.views.gtk3.widgets import RAMSTKEntry as RAMSTKEntry

# RAMSTK Local Imports
from .panels import RAMSTKAssessmentInputPanel as RAMSTKAssessmentInputPanel
from .panels import RAMSTKAssessmentResultPanel as RAMSTKAssessmentResultPanel

class AssessmentInputPanel(RAMSTKAssessmentInputPanel):
    _dic_quality: Dict[int, List[List[str]]] = ...
    _dic_specifications: Dict[int, List[List[str]]] = ...
    _dic_types: Dict[int, List[List[str]]] = ...
    _dic_styles: Dict[int, Dict[int, List[List[str]]]] = ...
    _dic_construction: Dict[int, List[List[str]]] = ...
    _dic_attribute_keys: Any = ...
    _lst_labels: Any = ...
    _lst_tooltips: Any = ...
    cmbConstruction: Any = ...
    cmbSpecification: Any = ...
    cmbStyle: Any = ...
    cmbType: Any = ...
    txtNElements: Any = ...
    txtResistance: Any = ...
    _dic_attribute_updater: Any = ...
    _lst_widgets: Any = ...

    def __init__(self) -> None:
        ...

    def do_load_comboboxes(self, subcategory_id: int) -> None:
        ...

    def _do_load_panel(self, attributes: Dict[str, Any]) -> None:
        ...

    def _do_set_sensitive(self) -> None:
        ...

    def __do_load_construction_combo(self) -> None:
        ...

    def __do_load_quality_combo(self) -> None:
        ...

    def __do_load_specification_combo(self) -> None:
        ...

    def __do_load_style_combo(self) -> None:
        ...

    def __do_load_type_combo(self) -> None:
        ...

    def __do_set_construction_combo_sensitive(self) -> None:
        ...

    def __do_set_elements_entry_sensitive(self) -> None:
        ...

    def __do_set_specification_combo_sensitive(self) -> None:
        ...

    def __do_set_style_combo_sensitive(self) -> None:
        ...

    def __do_set_type_combo_sensitive(self) -> None:
        ...

    def __set_callbacks(self) -> None:
        ...

    def __set_properties(self) -> None:
        ...


class AssessmentResultPanel(RAMSTKAssessmentResultPanel):
    _dic_part_stress: Any = ...
    _lst_labels: Any = ...
    _lst_tooltips: Any = ...
    txtPiC: Any = ...
    txtPiNR: Any = ...
    txtPiR: Any = ...
    txtPiT: Any = ...
    txtPiTAPS: Any = ...
    txtPiV: Any = ...
    _lst_widgets: Any = ...

    def __init__(self) -> None:
        ...

    def _do_load_panel(self, attributes: Dict[str, Any]) -> None:
        ...

    def _do_set_sensitive(self) -> None:
        ...

    def __do_set_pic_sensitive(self) -> None:
        ...

    def __do_set_pie_sensitive(self) -> None:
        ...

    def __do_set_pir_sensitive(self) -> None:
        ...

    def __do_set_pit_pinr_sensitive(self) -> None:
        ...

    def __do_set_pitaps_piv_sensitive(self) -> None:
        ...
