from .panels import RAMSTKAssessmentInputPanel as RAMSTKAssessmentInputPanel, RAMSTKAssessmentResultPanel as RAMSTKAssessmentResultPanel
from ramstk.views.gtk3.widgets import RAMSTKComboBox as RAMSTKComboBox, RAMSTKEntry as RAMSTKEntry
from typing import Any

class AssessmentInputPanel(RAMSTKAssessmentInputPanel):
    cmbConstruction: Any = ...
    cmbSpecification: Any = ...
    cmbStyle: Any = ...
    cmbType: Any = ...
    txtNElements: Any = ...
    txtResistance: Any = ...
    def __init__(self) -> None: ...
    def do_load_comboboxes(self, subcategory_id: int) -> None: ...

class AssessmentResultPanel(RAMSTKAssessmentResultPanel):
    txtPiC: Any = ...
    txtPiNR: Any = ...
    txtPiR: Any = ...
    txtPiT: Any = ...
    txtPiTAPS: Any = ...
    txtPiV: Any = ...
    def __init__(self) -> None: ...
