from ramstk.views.gtk3.widgets import RAMSTKComboBox as RAMSTKComboBox, RAMSTKEntry as RAMSTKEntry, RAMSTKLabel as RAMSTKLabel, RAMSTKPanel as RAMSTKPanel
from typing import Any

class AssessmentInputPanel(RAMSTKPanel):
    cmbConstruction: Any = ...
    cmbQuality: Any = ...
    cmbSpecification: Any = ...
    cmbStyle: Any = ...
    cmbType: Any = ...
    txtNElements: Any = ...
    txtResistance: Any = ...
    def __init__(self) -> None: ...
    def do_load_comboboxes(self, subcategory_id: int) -> None: ...

class AssessmentResultPanel(RAMSTKPanel):
    lblModel: Any = ...
    txtLambdaB: Any = ...
    txtPiC: Any = ...
    txtPiE: Any = ...
    txtPiNR: Any = ...
    txtPiQ: Any = ...
    txtPiR: Any = ...
    txtPiT: Any = ...
    txtPiTAPS: Any = ...
    txtPiV: Any = ...
    def __init__(self) -> None: ...
