# Standard Library Imports
from typing import Any, Dict

# RAMSTK Package Imports
from ramstk.views.gtk3 import _ as _
from ramstk.views.gtk3.widgets import RAMSTKComboBox as RAMSTKComboBox
from ramstk.views.gtk3.widgets import RAMSTKEntry as RAMSTKEntry

# RAMSTK Local Imports
from .panels import RAMSTKAssessmentInputPanel as RAMSTKAssessmentInputPanel
from .panels import RAMSTKAssessmentResultPanel as RAMSTKAssessmentResultPanel

class AssessmentInputPanel(RAMSTKAssessmentInputPanel):
    _dic_quality: Any = ...
    _dic_types: Any = ...
    _dic_applications: Any = ...
    _dic_matchings: Any = ...
    _lst_packages: Any = ...
    _dic_attribute_keys: Any = ...
    _lst_labels: Any = ...
    _lst_tooltips: Any = ...
    cmbApplication: Any = ...
    cmbConstruction: Any = ...
    cmbMatching: Any = ...
    cmbPackage: Any = ...
    cmbType: Any = ...
    txtFrequencyOperating: Any = ...
    txtNElements: Any = ...
    txtThetaJC: Any = ...
    _dic_attribute_updater: Any = ...
    _lst_widgets: Any = ...

    def __init__(self) -> None:
        ...

    def do_load_comboboxes(self, subcategory_id: int) -> None:
        ...

    def _do_load_panel(self, attributes: Dict[str, Any]) -> None:
        ...

    def _do_set_sensitive(self) -> None:
        ...

    def __do_load_application(self) -> None:
        ...

    def __do_load_construction(self) -> None:
        ...

    def __do_load_matching(self) -> None:
        ...

    def __do_load_quality(self) -> None:
        ...

    def __do_load_type(self) -> None:
        ...

    def __do_set_application_sensitive(self) -> None:
        ...

    def __do_set_construction_sensitive(self) -> None:
        ...

    def __do_set_elements_sensitive(self) -> None:
        ...

    def __do_set_matching_sensitive(self) -> None:
        ...

    def __do_set_op_freq_sensitive(self) -> None:
        ...

    def __do_set_type_sensitive(self) -> None:
        ...

    def __set_callbacks(self) -> None:
        ...

    def __set_properties(self) -> None:
        ...


class AssessmentResultPanel(RAMSTKAssessmentResultPanel):
    _dic_part_stress: Dict[int, str] = ...
    _lst_labels: Any = ...
    _lst_tooltips: Any = ...
    txtPiA: Any = ...
    txtPiC: Any = ...
    txtPiI: Any = ...
    txtPiM: Any = ...
    txtPiP: Any = ...
    txtPiR: Any = ...
    txtPiS: Any = ...
    txtPiT: Any = ...
    _lst_widgets: Any = ...

    def __init__(self) -> None:
        ...

    def _do_load_panel(self, attributes: Dict[str, Any]) -> None:
        ...

    def _do_set_sensitive(self) -> None:
        ...

    def __do_set_pi_a_sensitive(self) -> None:
        ...

    def __do_set_pi_c_sensitive(self) -> None:
        ...

    def __do_set_pi_e_sensitive(self) -> None:
        ...

    def __do_set_pi_i_sensitive(self) -> None:
        ...

    def __do_set_pi_m_sensitive(self) -> None:
        ...

    def __do_set_pi_p_sensitive(self) -> None:
        ...

    def __do_set_pi_r_sensitive(self) -> None:
        ...

    def __do_set_pi_s_sensitive(self) -> None:
        ...

    def __do_set_pi_t_sensitive(self) -> None:
        ...
