from ramstk.views.gtk3.widgets import RAMSTKComboBox as RAMSTKComboBox, RAMSTKEntry as RAMSTKEntry, RAMSTKLabel as RAMSTKLabel, RAMSTKPanel as RAMSTKPanel
from typing import Any

class AssessmentInputPanel(RAMSTKPanel):
    cmbApplication: Any = ...
    cmbConstruction: Any = ...
    cmbContactForm: Any = ...
    cmbQuality: Any = ...
    txtNCycles: Any = ...
    txtNElements: Any = ...
    def __init__(self) -> None: ...
    def do_load_comboboxes(self, subcategory_id: int) -> None: ...

class AssessmentResultPanel(RAMSTKPanel):
    lblModel: Any = ...
    txtLambdaB: Any = ...
    txtPiC: Any = ...
    txtPiCYC: Any = ...
    txtPiE: Any = ...
    txtPiL: Any = ...
    txtPiN: Any = ...
    txtPiQ: Any = ...
    txtPiU: Any = ...
    def __init__(self) -> None: ...
