from .panels import RAMSTKAssessmentInputPanel as RAMSTKAssessmentInputPanel, RAMSTKAssessmentResultPanel as RAMSTKAssessmentResultPanel
from ramstk.views.gtk3.widgets import RAMSTKComboBox as RAMSTKComboBox, RAMSTKEntry as RAMSTKEntry
from typing import Any

class AssessmentInputPanel(RAMSTKAssessmentInputPanel):
    cmbApplication: Any = ...
    cmbConstruction: Any = ...
    cmbContactForm: Any = ...
    txtNCycles: Any = ...
    txtNElements: Any = ...
    def __init__(self) -> None: ...
    def do_load_comboboxes(self, subcategory_id: int) -> None: ...

class AssessmentResultPanel(RAMSTKAssessmentResultPanel):
    txtPiC: Any = ...
    txtPiCYC: Any = ...
    txtPiL: Any = ...
    txtPiN: Any = ...
    txtPiU: Any = ...
    def __init__(self) -> None: ...
