# Standard Library Imports
from typing import Any, Dict

PART_COUNT_LAMBDA_B: Any
PART_COUNT_PI_Q: Any
PART_STRESS_PI_Q: Any
PI_C: Any
PI_E: Any
PI_R: Any
PI_V: Any
REF_TEMPS: Dict[int, float]
REF_TEMPS_FILM: Dict[int, float]

def calculate_part_count(**attributes: Dict[str, Any]) -> float: ...
def calculate_part_stress(**attributes: Dict[str, Any]) -> Dict[str, Any]: ...
def calculate_part_stress_lambda_b(attributes: Dict[str, Any]) -> Dict[str, Any]: ...
def calculate_temperature_factor(attributes: Dict[str, Any]) -> Dict[str, Any]: ...
def get_part_count_lambda_b(attributes: Dict[str, Any]) -> Dict[str, Any]: ...
def get_resistance_factor(attributes: Dict[str, Any]) -> Dict[str, Any]: ...
def get_voltage_factor(attributes: Dict[str, Any]) -> Dict[str, Any]: ...
