from ramstk.configuration import RAMSTKUserConfiguration as RAMSTKUserConfiguration
from ramstk.db import BaseDatabase as BaseDatabase
from ramstk.exceptions import DataAccessError as DataAccessError
from typing import Any, Dict

class RAMSTKProgramManager:
    dic_managers: Any = ...
    user_configuration: Any = ...
    program_dao: Any = ...
    def __init__(self) -> None: ...
    def do_create_program(self, program_db: BaseDatabase, database: Dict) -> None: ...
    def do_open_program(self, program_db: BaseDatabase, database: Dict[str, str]) -> None: ...
    def do_close_program(self) -> None: ...
    @staticmethod
    def do_save_program() -> None: ...
