# Standard Library Imports
import gettext
from datetime import date
from typing import Any, Callable

_ = gettext.gettext

def date_to_ordinal(date_string: str) -> int: ...
def deprecated(func: Callable) -> Callable: ...
def dir_exists(directory: str) -> bool: ...
def do_subscribe_to_messages(messages) -> None: ...
def file_exists(_file: str) -> bool: ...
def none_to_default(
    field: bool | date | float | int | str | None,
    default: bool | date | float | int | str | None,
) -> bool | date | float | int | str | None: ...
def none_to_string(string: None | str) -> str: ...
def ordinal_to_date(ordinal: int) -> str: ...
def split_string(string: str) -> list[str]: ...
def boolean_to_integer(boolean: bool) -> int: ...
def integer_to_boolean(integer: int) -> bool: ...
def sort_dict(
    dictionary, by_value: bool = True, reverse: bool = False
) -> dict[Any, Any]: ...
def string_to_boolean(string: bool | str) -> bool: ...
def get_install_prefix() -> str: ...
