# Standard Library Imports
from typing import Any, Dict, List

# Third Party Imports
import treelib

# RAMSTK Package Imports
from ramstk.configuration import (
    RAMSTKUserConfiguration as RAMSTKUserConfiguration
)
from ramstk.logger import RAMSTKLogManager as RAMSTKLogManager
from ramstk.views.gtk3 import GdkPixbuf as GdkPixbuf
from ramstk.views.gtk3 import Gtk as Gtk
from ramstk.views.gtk3 import _ as _
from ramstk.views.gtk3.assistants import (
    AddStressTestMethod as AddStressTestMethod
)
from ramstk.views.gtk3.widgets import RAMSTKLabel as RAMSTKLabel
from ramstk.views.gtk3.widgets import RAMSTKPanel as RAMSTKPanel
from ramstk.views.gtk3.widgets import RAMSTKWorkView as RAMSTKWorkView

def get_indenture_level(record_id: str) -> str:
    ...


class PoFPanel(RAMSTKPanel):
    _dic_column_masks: Dict[str, List[bool]] = ...
    _dic_headings: Dict[str, List[str]] = ...
    _dic_attribute_keys: Any = ...
    _title: Any = ...
    dic_damage_models: Any = ...
    dic_icons: Any = ...
    dic_load_history: Any = ...
    dic_measurable_parameters: Any = ...

    def __init__(self) -> None:
        ...

    def do_load_combobox(self) -> None:
        ...

    def do_set_callbacks(self) -> None:
        ...

    def _do_load_panel(self,
                       tree: treelib.Tree,
                       row: Gtk.TreeIter = ...) -> None:
        ...

    def _do_load_row(self, node: treelib.Node,
                     row: Gtk.TreeIter) -> Gtk.TreeIter:
        ...

    def _on_delete_insert_pof(self, node_id: int, tree: treelib.Tree) -> None:
        ...

    _record_id: Any = ...

    def _on_row_change(self, selection: Gtk.TreeSelection) -> None:
        ...

    def __do_load_damage_models(self) -> None:
        ...

    def __do_load_load_history(self) -> None:
        ...

    def __do_load_measureable_parameters(self) -> None:
        ...

    def __do_load_mechanism(self, node: treelib.Node,
                            row: Gtk.TreeIter) -> Gtk.TreeIter:
        ...

    def __do_load_mode(self, node: treelib.Node,
                       row: Gtk.TreeIter) -> Gtk.TreeIter:
        ...

    def __do_load_opload(self, node: treelib.Node,
                         row: Gtk.TreeIter) -> Gtk.TreeIter:
        ...

    def __do_load_opstress(self, node: treelib.Node,
                           row: Gtk.TreeIter) -> Gtk.TreeIter:
        ...

    def __do_load_test_method(self, node: treelib.Node,
                              row: Gtk.TreeIter) -> Gtk.TreeIter:
        ...

    def __do_set_properties(self) -> None:
        ...

    def __get_cell_model(self, column: Gtk.TreeViewColumn) -> Gtk.TreeModel:
        ...


class PoF(RAMSTKWorkView):
    _module: str = ...
    _pixbuf: bool = ...
    _tablabel: Any = ...
    _tabtooltip: Any = ...
    _lst_callbacks: Any = ...
    _lst_icons: Any = ...
    _lst_mnu_labels: Any = ...
    _lst_tooltips: Any = ...
    _pnlPanel: Any = ...

    def __init__(self, configuration: RAMSTKUserConfiguration,
                 logger: RAMSTKLogManager) -> None:
        ...

    def _do_request_delete(self, __button: Gtk.ToolButton) -> None:
        ...

    def _do_request_insert_child(self, __button: Gtk.ToolButton) -> None:
        ...

    def _do_request_insert_sibling(self, __button: Gtk.ToolButton) -> None:
        ...

    def _do_request_update(self, __button: Gtk.ToolButton) -> None:
        ...

    def _do_request_update_all(self, __button: Gtk.ToolButton) -> None:
        ...

    def _on_request_insert_opstress_method(self) -> str:
        ...

    def __do_set_callbacks(self) -> None:
        ...

    def __make_ui(self) -> None:
        ...
