# Standard Library Imports
from typing import Any, Dict, Tuple

# RAMSTK Package Imports
from ramstk.configuration import (
    RAMSTKUserConfiguration as RAMSTKUserConfiguration
)
from ramstk.logger import RAMSTKLogManager as RAMSTKLogManager
from ramstk.views.gtk3 import Gdk as Gdk
from ramstk.views.gtk3 import Gtk as Gtk
from ramstk.views.gtk3.widgets import RAMSTKButton as RAMSTKButton
from ramstk.views.gtk3.widgets import RAMSTKComboBox as RAMSTKComboBox
from ramstk.views.gtk3.widgets import RAMSTKDateSelect as RAMSTKDateSelect
from ramstk.views.gtk3.widgets import RAMSTKEntry as RAMSTKEntry
from ramstk.views.gtk3.widgets import RAMSTKFrame as RAMSTKFrame
from ramstk.views.gtk3.widgets import RAMSTKPanel as RAMSTKPanel
from ramstk.views.gtk3.widgets import RAMSTKPlot as RAMSTKPlot
from ramstk.views.gtk3.widgets import RAMSTKSpinButton as RAMSTKSpinButton
from ramstk.views.gtk3.widgets import RAMSTKTextView as RAMSTKTextView
from ramstk.views.gtk3.widgets import RAMSTKWorkView as RAMSTKWorkView

class TaskDescriptionPanel(RAMSTKPanel):
    fmt: str = ...
    btnEndDate: Any = ...
    btnStartDate: Any = ...
    cmbTaskType: Any = ...
    cmbMeasurementUnit: Any = ...
    spnStatus: Any = ...
    txtCode: Any = ...
    txtName: Any = ...
    txtMaxAcceptable: Any = ...
    txtMeanAcceptable: Any = ...
    txtMinAcceptable: Any = ...
    txtVarAcceptable: Any = ...
    txtSpecification: Any = ...
    txtTask: Any = ...
    txtEndDate: Any = ...
    txtStartDate: Any = ...
    def __init__(self) -> None: ...
    def do_load_measurement_units(self, measurement_unit: Dict[int, Tuple[str, str]]) -> None: ...
    def do_load_validation_types(self, validation_type: Dict[int, Tuple[str, str]]) -> None: ...

class TaskEffortPanel(RAMSTKPanel):
    fmt: str = ...
    txtMinTime: Any = ...
    txtExpTime: Any = ...
    txtMaxTime: Any = ...
    txtMinCost: Any = ...
    txtExpCost: Any = ...
    txtMaxCost: Any = ...
    txtMeanTimeLL: Any = ...
    txtMeanTime: Any = ...
    txtMeanTimeUL: Any = ...
    txtMeanCostLL: Any = ...
    txtMeanCost: Any = ...
    txtMeanCostUL: Any = ...
    def __init__(self) -> None: ...

class ProgramEffortPanel(RAMSTKPanel):
    fmt: str = ...
    txtProjectTimeLL: Any = ...
    txtProjectTime: Any = ...
    txtProjectTimeUL: Any = ...
    txtProjectCostLL: Any = ...
    txtProjectCost: Any = ...
    txtProjectCostUL: Any = ...
    def __init__(self) -> None: ...

class GeneralData(RAMSTKWorkView):
    def __init__(self, configuration: RAMSTKUserConfiguration, logger: RAMSTKLogManager) -> None: ...

class BurndownCurve(RAMSTKWorkView):
    pltPlot: Any = ...
    def __init__(self, configuration: RAMSTKUserConfiguration, logger: RAMSTKLogManager) -> None: ...
