from ramstk.configuration import RAMSTKUserConfiguration as RAMSTKUserConfiguration
from ramstk.logger import RAMSTKLogManager as RAMSTKLogManager
from ramstk.views.gtk3 import Gdk as Gdk, Gtk as Gtk
from ramstk.views.gtk3.widgets import RAMSTKButton as RAMSTKButton, RAMSTKComboBox as RAMSTKComboBox, RAMSTKDateSelect as RAMSTKDateSelect, RAMSTKEntry as RAMSTKEntry, RAMSTKFrame as RAMSTKFrame, RAMSTKPanel as RAMSTKPanel, RAMSTKPlot as RAMSTKPlot, RAMSTKSpinButton as RAMSTKSpinButton, RAMSTKTextView as RAMSTKTextView, RAMSTKWorkView as RAMSTKWorkView
from typing import Any, Dict, Tuple

class TaskDescriptionPanel(RAMSTKPanel):
    fmt: str = ...
    btnEndDate: Any = ...
    btnStartDate: Any = ...
    cmbTaskType: Any = ...
    cmbMeasurementUnit: Any = ...
    spnStatus: Any = ...
    txtCode: Any = ...
    txtName: Any = ...
    txtMaxAcceptable: Any = ...
    txtMeanAcceptable: Any = ...
    txtMinAcceptable: Any = ...
    txtVarAcceptable: Any = ...
    txtSpecification: Any = ...
    txtTask: Any = ...
    txtEndDate: Any = ...
    txtStartDate: Any = ...
    def __init__(self) -> None: ...
    def do_load_measurement_units(self, measurement_unit: Dict[int, Tuple[str, str]]) -> None: ...
    def do_load_validation_types(self, validation_type: Dict[int, Tuple[str, str]]) -> None: ...

class TaskEffortPanel(RAMSTKPanel):
    fmt: str = ...
    txtMinTime: Any = ...
    txtExpTime: Any = ...
    txtMaxTime: Any = ...
    txtMinCost: Any = ...
    txtExpCost: Any = ...
    txtMaxCost: Any = ...
    txtMeanTimeLL: Any = ...
    txtMeanTime: Any = ...
    txtMeanTimeUL: Any = ...
    txtMeanCostLL: Any = ...
    txtMeanCost: Any = ...
    txtMeanCostUL: Any = ...
    def __init__(self) -> None: ...

class ProgramEffortPanel(RAMSTKPanel):
    fmt: str = ...
    txtProjectTimeLL: Any = ...
    txtProjectTime: Any = ...
    txtProjectTimeUL: Any = ...
    txtProjectCostLL: Any = ...
    txtProjectCost: Any = ...
    txtProjectCostUL: Any = ...
    def __init__(self) -> None: ...

class GeneralData(RAMSTKWorkView):
    def __init__(self, configuration: RAMSTKUserConfiguration, logger: RAMSTKLogManager) -> None: ...

class BurndownCurve(RAMSTKWorkView):
    pltPlot: Any = ...
    def __init__(self, configuration: RAMSTKUserConfiguration, logger: RAMSTKLogManager) -> None: ...
