# Standard Library Imports
from typing import Any

# Third Party Imports
from sqlalchemy.orm import relationship

# RAMSTK Package Imports
from ramstk.db import RAMSTK_BASE as RAMSTK_BASE
from ramstk.models import RAMSTKBaseTable as RAMSTKBaseTable

class RAMSTKMission(RAMSTK_BASE, RAMSTKBaseTable):
    __defaults__: Any = ...
    __tablename__: str = ...
    __table_args__: Any = ...
    revision_id: Any = ...
    mission_id: Any = ...
    description: Any = ...
    mission_time: Any = ...
    time_units: Any = ...
    revision: relationship = ...
    phase: relationship = ...
    is_mission: bool = ...
    is_phase: bool = ...
    is_env: bool = ...

    def get_attributes(self):
        ...
