from ramstk.configuration import RAMSTKUserConfiguration as RAMSTKUserConfiguration
from ramstk.logger import RAMSTKLogManager as RAMSTKLogManager
from ramstk.views.gtk3 import Gtk as Gtk
from ramstk.views.gtk3.widgets import RAMSTKEntry as RAMSTKEntry, RAMSTKPanel as RAMSTKPanel, RAMSTKTextView as RAMSTKTextView, RAMSTKWorkView as RAMSTKWorkView
from typing import Any

class GeneralDataPanel(RAMSTKPanel):
    txtCode: Any = ...
    txtName: Any = ...
    txtRemarks: Any = ...
    def __init__(self) -> None: ...

class GeneralData(RAMSTKWorkView):
    def __init__(self, configuration: RAMSTKUserConfiguration, logger: RAMSTKLogManager) -> None: ...
