# Standard Library Imports
from typing import Any

# Third Party Imports
from pubsub import pub as pub

# RAMSTK Package Imports
from ramstk.controllers import RAMSTKDataManager as RAMSTKDataManager
from ramstk.models.commondb import RAMSTKSiteInfo as RAMSTKSiteInfo

class DataManager(RAMSTKDataManager):
    _db_id_colname: str = ...
    _db_tablename: str = ...
    _tag: str = ...
    _lst_id_columns: Any = ...
    _record: Any = ...
    pkey: str = ...
    def __init__(self, **kwargs: Any) -> None: ...
