# Standard Library Imports
from typing import Any, Dict

# RAMSTK Package Imports
from ramstk.analyses import stress as stress
from ramstk.models import RAMSTKBaseTable as RAMSTKBaseTable
from ramstk.models.programdb import RAMSTKDesignElectric as RAMSTKDesignElectric

class RAMSTKDesignElectricTable(RAMSTKBaseTable):
    _db_id_colname: str = ...
    _db_tablename: str = ...
    _select_msg: str = ...
    _tag: str = ...
    _lst_id_columns: Any = ...
    _record: Any = ...
    pkey: str = ...
    def __init__(self, **kwargs: Dict[Any, Any]) -> None: ...
    _parent_id: Any = ...
    def do_get_new_record(self, attributes: Dict[str, Any]) -> object: ...
    def _do_calculate_current_ratio(self, node_id: int) -> None: ...
    def _do_calculate_power_ratio(self, node_id: int) -> None: ...
    def _do_calculate_voltage_ratio(self, node_id: int) -> None: ...
