# Standard Library Imports
from typing import Any, Dict

# RAMSTK Package Imports
from ramstk.controllers import RAMSTKDataManager as RAMSTKDataManager
from ramstk.exceptions import DataAccessError as DataAccessError
from ramstk.models.programdb import RAMSTKMode as RAMSTKMode

class DataManager(RAMSTKDataManager):
    _db_id_colname: str = ...
    _db_tablename: str = ...
    _tag: str = ...
    _pkey: Any = ...
    def __init__(self, **kwargs: Dict[str, Any]) -> None: ...
    _revision_id: Any = ...
    _parent_id: Any = ...
    last_id: Any = ...
    def do_select_all(self, attributes: Dict[str, Any]) -> None: ...
    def _do_insert_mode(self) -> None: ...
