# Standard Library Imports
from typing import Any

# Third Party Imports
import treelib
from _typeshed import Incomplete

# RAMSTK Package Imports
from ramstk.utilities import do_subscribe_to_messages as do_subscribe_to_messages
from ramstk.views.gtk3 import GdkPixbuf as GdkPixbuf
from ramstk.views.gtk3 import Gtk as Gtk
from ramstk.views.gtk3 import _ as _
from ramstk.views.gtk3.widgets import RAMSTKCellRendererCombo as RAMSTKCellRendererCombo
from ramstk.views.gtk3.widgets import RAMSTKCellRendererText as RAMSTKCellRendererText
from ramstk.views.gtk3.widgets import (
    RAMSTKCellRendererToggle as RAMSTKCellRendererToggle,
)
from ramstk.views.gtk3.widgets import RAMSTKTreePanel as RAMSTKTreePanel
from ramstk.views.gtk3.widgets import WidgetConfig as WidgetConfig
from ramstk.views.gtk3.widgets import make_widget_config as make_widget_config

class FMEATreePanel(RAMSTKTreePanel):
    _dic_visible_mask: dict[str, list[bool]]
    _select_msg: str
    _tag: str
    _title: Incomplete
    lst_control_types: Incomplete
    _dic_mission_phases: dict[str, list[str]]
    _lst_missions: list[str]
    _lst_widget_configuration: list[WidgetConfig]
    _filtered_tree: bool
    _on_edit_message: str
    dic_icons: dict[str, str]
    clear_modes: bool
    level: str
    def __init__(self) -> None: ...
    def do_filter_tree(
        self, model: Gtk.TreeModel, row: Gtk.TreeIter, data: Any
    ) -> bool: ...
    def do_get_fmea_level(self, model: Gtk.TreeModel, row: Gtk.TreeIter) -> None: ...
    def do_load_comboboxes(self) -> None: ...
    def _on_cell_edit(
        self, cell: Gtk.CellRenderer, path: str, new_text: str, key: str, message: str
    ) -> None: ...
    def _on_mission_change(
        self, /, __combo: RAMSTKCellRendererCombo, path: str, new_text: str
    ) -> None: ...
    _record_id: Incomplete
    def _on_row_change(self, selection: Gtk.TreeSelection) -> None: ...
    _parent_id: Incomplete
    def _on_select_hardware(self, attributes: dict[str, int | float | str]) -> None: ...
    def __do_clear_modes(self) -> None: ...
    def __do_clear_modes_on_category_change(
        self, attributes: dict[str, int]
    ) -> None: ...
    def __do_clear_modes_on_subcategory_change(self, subcategory_id: int) -> None: ...
    def __do_get_rpn_names(self, entity: object) -> tuple[str, str, str, str]: ...
    def __do_load_action(
        self, node: treelib.Node, row: Gtk.TreeIter
    ) -> Gtk.TreeIter: ...
    def do_load_action_category(
        self, categories: dict[int, tuple[str, str, int]]
    ) -> None: ...
    def do_load_action_status(self, status: dict[int, tuple[str, str]]) -> None: ...
    def __do_load_cause(
        self, node: treelib.Node, row: Gtk.TreeIter
    ) -> Gtk.TreeIter: ...
    def __do_load_control(
        self, node: treelib.Node, row: Gtk.TreeIter
    ) -> Gtk.TreeIter: ...
    def _do_load_control_types(self) -> None: ...
    def __do_load_mechanism(
        self, node: treelib.Node, row: Gtk.TreeIter
    ) -> Gtk.TreeIter: ...
    def __do_load_missions(
        self, tree: treelib.Tree = ..., node_id: str = "", row: Gtk.TreeIter = None
    ) -> None: ...
    def __do_load_mission_phases(self, mission: str) -> None: ...
    def __do_load_mode(self, node: treelib.Node, row: Gtk.TreeIter) -> Gtk.TreeIter: ...
    def do_load_mode_probability(
        self, probabilities: list[list[str | int]]
    ) -> None: ...
    def do_load_rpn_detection(self, detections: dict[int, tuple[str]]) -> None: ...
    def do_load_rpn_occurrence(self, occurrences: dict[int, tuple[str]]) -> None: ...
    def do_load_rpn_severity(self, severities: dict[int, tuple[str]]) -> None: ...
    def do_load_severity_class(self, severities: list[list[int | str]]) -> None: ...
    def do_load_users(
        self, users: dict[int, tuple[str, str, str, str, str]]
    ) -> None: ...
