from .Capacitor import CapacitorAssessmentInputs as wvwCapacitorAI
from .Capacitor import CapacitorAssessmentResults as wvwCapacitorAR
from .Connection import ConnectionAssessmentInputs as wvwConnectionAI
from .Connection import ConnectionAssessmentResults as wvwConnectionAR
from .Inductor import InductorAssessmentInputs as wvwInductorAI
from .Inductor import InductorAssessmentResults as wvwInductorAR
from .IntegratedCircuit import AssessmentInputs as wvwIntegratedCircuitAI
from .IntegratedCircuit import AssessmentResults as wvwIntegratedCircuitAR
from .Meter import AssessmentInputs as wvwMeterAI
from .Meter import AssessmentResults as wvwMeterAR
from .Miscellaneous import AssessmentInputs as wvwMiscellaneousAI
from .Miscellaneous import AssessmentResults as wvwMiscellaneousAR
from .Relay import AssessmentInputs as wvwRelayAI
from .Relay import AssessmentResults as wvwRelayAR
from .Resistor import AssessmentInputs as wvwResistorAI
from .Resistor import AssessmentResults as wvwResistorAR
from .Semiconductor import AssessmentInputs as wvwSemiconductorAI
from .Semiconductor import AssessmentResults as wvwSemiconductorAR
from .Switch import AssessmentInputs as wvwSwitchAI
from .Switch import AssessmentResults as wvwSwitchAR
