# Standard Library Imports
from typing import Any, Dict, Tuple

# RAMSTK Package Imports
from ramstk.configuration import (
    RAMSTKUserConfiguration as RAMSTKUserConfiguration
)
from ramstk.logger import RAMSTKLogManager as RAMSTKLogManager
from ramstk.views.gtk3 import Gdk as Gdk
from ramstk.views.gtk3 import Gtk as Gtk
from ramstk.views.gtk3.widgets import RAMSTKButton as RAMSTKButton
from ramstk.views.gtk3.widgets import RAMSTKCheckButton as RAMSTKCheckButton
from ramstk.views.gtk3.widgets import RAMSTKComboBox as RAMSTKComboBox
from ramstk.views.gtk3.widgets import RAMSTKDateSelect as RAMSTKDateSelect
from ramstk.views.gtk3.widgets import RAMSTKEntry as RAMSTKEntry
from ramstk.views.gtk3.widgets import RAMSTKPanel as RAMSTKPanel
from ramstk.views.gtk3.widgets import RAMSTKTextView as RAMSTKTextView
from ramstk.views.gtk3.widgets import RAMSTKWorkView as RAMSTKWorkView

class GeneralDataPanel(RAMSTKPanel):
    btnValidateDate: Any = ...
    chkDerived: Any = ...
    chkValidated: Any = ...
    cmbOwner: Any = ...
    cmbRequirementType: Any = ...
    cmbPriority: Any = ...
    txtCode: Any = ...
    txtFigNum: Any = ...
    txtName: Any = ...
    txtPageNum: Any = ...
    txtSpecification: Any = ...
    txtValidatedDate: Any = ...
    def __init__(self) -> None: ...
    def do_load_priorities(self) -> None: ...
    def do_load_requirement_types(self, requirement_types: Dict[int, Tuple[str]]) -> None: ...
    def do_load_workgroups(self, workgroups: Dict[int, Tuple[str]]) -> None: ...

class ClarityPanel(RAMSTKPanel):
    chkClarityQ0: Any = ...
    chkClarityQ1: Any = ...
    chkClarityQ2: Any = ...
    chkClarityQ3: Any = ...
    chkClarityQ4: Any = ...
    chkClarityQ5: Any = ...
    chkClarityQ6: Any = ...
    chkClarityQ7: Any = ...
    chkClarityQ8: Any = ...
    def __init__(self) -> None: ...

class CompletenessPanel(RAMSTKPanel):
    chkCompleteQ0: Any = ...
    chkCompleteQ1: Any = ...
    chkCompleteQ2: Any = ...
    chkCompleteQ3: Any = ...
    chkCompleteQ4: Any = ...
    chkCompleteQ5: Any = ...
    chkCompleteQ6: Any = ...
    chkCompleteQ7: Any = ...
    chkCompleteQ8: Any = ...
    chkCompleteQ9: Any = ...
    def __init__(self) -> None: ...

class ConsistencyPanel(RAMSTKPanel):
    chkConsistentQ0: Any = ...
    chkConsistentQ1: Any = ...
    chkConsistentQ2: Any = ...
    chkConsistentQ3: Any = ...
    chkConsistentQ4: Any = ...
    chkConsistentQ5: Any = ...
    chkConsistentQ6: Any = ...
    chkConsistentQ7: Any = ...
    chkConsistentQ8: Any = ...
    def __init__(self) -> None: ...

class VerifiabilityPanel(RAMSTKPanel):
    chkVerifiableQ0: Any = ...
    chkVerifiableQ1: Any = ...
    chkVerifiableQ2: Any = ...
    chkVerifiableQ3: Any = ...
    chkVerifiableQ4: Any = ...
    chkVerifiableQ5: Any = ...
    def __init__(self) -> None: ...

class GeneralData(RAMSTKWorkView):
    def __init__(self, configuration: RAMSTKUserConfiguration, logger: RAMSTKLogManager) -> None: ...

class RequirementAnalysis(RAMSTKWorkView):
    def __init__(self, configuration: RAMSTKUserConfiguration, logger: RAMSTKLogManager) -> None: ...
