from ramstk.configuration import RAMSTKUserConfiguration as RAMSTKUserConfiguration
from ramstk.logger import RAMSTKLogManager as RAMSTKLogManager
from ramstk.views.gtk3 import Gtk as Gtk
from ramstk.views.gtk3.assistants import EditFunction as EditFunction
from ramstk.views.gtk3.widgets import RAMSTKComboBox as RAMSTKComboBox, RAMSTKPanel as RAMSTKPanel, RAMSTKWorkView as RAMSTKWorkView
from typing import Any, List

class MethodPanel(RAMSTKPanel):
    cmbSimilarItemMethod: Any = ...
    def __init__(self) -> None: ...

class SimilarItemPanel(RAMSTKPanel):
    def __init__(self) -> None: ...
    def do_load_combobox(self) -> None: ...
    def do_refresh_functions(self, row: Gtk.TreeIter, function: List[str]) -> None: ...
    def do_set_callbacks(self) -> None: ...

class SimilarItem(RAMSTKWorkView):
    def __init__(self, configuration: RAMSTKUserConfiguration, logger: RAMSTKLogManager) -> None: ...
