# Standard Library Imports
from typing import Any, Dict, List

# RAMSTK Package Imports
from ramstk.configuration import (
    RAMSTKUserConfiguration as RAMSTKUserConfiguration
)
from ramstk.logger import RAMSTKLogManager as RAMSTKLogManager
from ramstk.views.gtk3 import Gtk as Gtk
from ramstk.views.gtk3 import _ as _
from ramstk.views.gtk3.widgets import RAMSTKPanel as RAMSTKPanel
from ramstk.views.gtk3.widgets import RAMSTKWorkView as RAMSTKWorkView

class HazOpsPanel(RAMSTKPanel):
    _dic_attribute_keys: Any = ...
    _parent_id: int = ...
    _title: Any = ...

    def __init__(self) -> None:
        ...

    def do_load_criticality(self, criticalities: List[List[str]]) -> None:
        ...

    def do_load_hazards(self, hazards: Dict[Any, Any]) -> None:
        ...

    def do_load_probability(self, probabilities: List[str]) -> None:
        ...

    def do_set_callbacks(self) -> None:
        ...

    def _do_clear_panel(self) -> None:
        ...

    def _do_load_panel(self, attributes: Dict[str, Any]) -> None:
        ...

    _record_id: Any = ...

    def _on_row_change(self, selection: Gtk.TreeSelection) -> None:
        ...

    def __do_set_properties(self) -> None:
        ...

    def __do_load_panel(self, node_id: int) -> None:
        ...


class HazOps(RAMSTKWorkView):
    _module: str = ...
    _tablabel: str = ...
    _tabtooltip: str = ...
    _lst_callbacks: Any = ...
    _lst_icons: Any = ...
    _lst_mnu_labels: Any = ...
    _lst_tooltips: Any = ...
    _pnlHazOps: Any = ...

    def __init__(self, configuration: RAMSTKUserConfiguration,
                 logger: RAMSTKLogManager) -> None:
        ...

    def _do_request_calculate(self, __button: Gtk.ToolButton) -> None:
        ...

    def _do_request_delete(self, __button: Gtk.ToolButton) -> None:
        ...

    def _do_request_insert(self, __button: Gtk.ToolButton) -> None:
        ...

    def _do_request_update(self, __button: Gtk.ToolButton) -> None:
        ...

    def _do_request_update_all(self, __button: Gtk.ToolButton) -> None:
        ...

    _revision_id: Any = ...
    _parent_id: Any = ...

    def __do_set_parent(self, attributes: Dict[str, Any]) -> None:
        ...

    def __make_ui(self) -> None:
        ...
