# Standard Library Imports
from typing import Any, Dict

# RAMSTK Package Imports
from ramstk.analyses import improvementfactor as improvementfactor
from ramstk.models import RAMSTKBaseTable as RAMSTKBaseTable
from ramstk.models.programdb import RAMSTKStakeholder as RAMSTKStakeholder

class DataManager(RAMSTKBaseTable):
    _db_id_colname: str = ...
    _db_tablename: str = ...
    _select_msg: str = ...
    _tag: str = ...
    _lst_id_columns: Any = ...
    _record: Any = ...
    pkey: str = ...
    def __init__(self, **kwargs: Dict[Any, Any]) -> None: ...
    def do_get_new_record(self, attributes: Dict[str, Any]) -> object: ...
    def do_calculate_stakeholder(self, node_id: int) -> None: ...
    def _do_calculate_improvement(self, node_id: int) -> None: ...
