# Standard Library Imports
from typing import Any, Tuple

def get_hazard_rate(
    shape: float, scale: float, time: float, location: float = ...
) -> float: ...
def get_mtbf(shape: float, scale: float, location: float = ...) -> float: ...
def get_survival(
    shape: float, scale: float, time: float, location: float = ...
) -> float: ...
def do_fit(data: Any, **kwargs: Any) -> Tuple[float, float, float]: ...
