from .components import capacitor as capacitor, connection as connection, inductor as inductor, integrated_circuit as integrated_circuit, meter as meter, miscellaneous as miscellaneous, relay as relay, resistor as resistor, semiconductor as semiconductor, switch as switch
from .components.panels import RAMSTKStressInputPanel as RAMSTKStressInputPanel, RAMSTKStressResultPanel as RAMSTKStressResultPanel
from ramstk.configuration import RAMSTKUserConfiguration as RAMSTKUserConfiguration, RAMSTK_ACTIVE_ENVIRONMENTS as RAMSTK_ACTIVE_ENVIRONMENTS, RAMSTK_DORMANT_ENVIRONMENTS as RAMSTK_DORMANT_ENVIRONMENTS, RAMSTK_HR_DISTRIBUTIONS as RAMSTK_HR_DISTRIBUTIONS, RAMSTK_HR_MODELS as RAMSTK_HR_MODELS, RAMSTK_HR_TYPES as RAMSTK_HR_TYPES
from ramstk.logger import RAMSTKLogManager as RAMSTKLogManager
from ramstk.views.gtk3 import Gtk as Gtk
from ramstk.views.gtk3.widgets import RAMSTKCheckButton as RAMSTKCheckButton, RAMSTKComboBox as RAMSTKComboBox, RAMSTKEntry as RAMSTKEntry, RAMSTKPanel as RAMSTKPanel, RAMSTKScrolledWindow as RAMSTKScrolledWindow, RAMSTKTextView as RAMSTKTextView, RAMSTKWorkView as RAMSTKWorkView
from typing import Any, Dict, List, Tuple

class GeneralDataPanel(RAMSTKPanel):
    dicSubcategories: Any = ...
    chkRepairable: Any = ...
    cmbCategory: Any = ...
    cmbSubcategory: Any = ...
    txtAltPartNum: Any = ...
    txtCompRefDes: Any = ...
    txtDescription: Any = ...
    txtFigureNumber: Any = ...
    txtLCN: Any = ...
    txtName: Any = ...
    txtPageNumber: Any = ...
    txtPartNumber: Any = ...
    txtRefDes: Any = ...
    txtSpecification: Any = ...
    def __init__(self) -> None: ...
    def do_load_categories(self, category: Dict[int, str]) -> None: ...

class LogisticsPanel(RAMSTKPanel):
    cmbCostType: Any = ...
    cmbManufacturer: Any = ...
    txtCAGECode: Any = ...
    txtCost: Any = ...
    txtNSN: Any = ...
    txtQuantity: Any = ...
    txtYearMade: Any = ...
    def __init__(self) -> None: ...
    def do_load_cost_types(self) -> None: ...
    def do_load_manufacturers(self, manufacturers: Dict[int, Tuple[str, str, str]]) -> None: ...

class MiscellaneousPanel(RAMSTKPanel):
    chkTagged: Any = ...
    txtAttachments: Any = ...
    txtRemarks: Any = ...
    def __init__(self) -> None: ...

class AssessmentInputPanel(RAMSTKPanel):
    cmbFailureDist: Any = ...
    cmbHRMethod: Any = ...
    cmbHRType: Any = ...
    txtAddAdjFactor: Any = ...
    txtFailLocation: Any = ...
    txtFailScale: Any = ...
    txtFailShape: Any = ...
    txtMultAdjFactor: Any = ...
    txtSpecifiedHt: Any = ...
    txtSpecifiedHtVar: Any = ...
    txtSpecifiedMTBF: Any = ...
    txtSpecifiedMTBFVar: Any = ...
    def __init__(self) -> None: ...
    def do_load_hr_distributions(self, distributions: List[str]) -> None: ...
    def do_load_hr_methods(self, methods: List[str]) -> None: ...
    def do_load_hr_types(self, hr_types: List[str]) -> None: ...

class EnvironmentalInputPanel(RAMSTKPanel):
    cmbActiveEnviron: Any = ...
    cmbDormantEnviron: Any = ...
    scwDesignRatings: Any = ...
    txtActiveTemp: Any = ...
    txtDormantTemp: Any = ...
    txtDutyCycle: Any = ...
    txtMissionTime: Any = ...
    def __init__(self) -> None: ...
    def do_load_environment_active(self, environments: List[str]) -> None: ...
    def do_load_environment_dormant(self, environments: List[str]) -> None: ...

class ReliabilityResultsPanel(RAMSTKPanel):
    txtActiveHt: Any = ...
    txtActiveHtVar: Any = ...
    txtDormantHt: Any = ...
    txtDormantHtVar: Any = ...
    txtLogisticsHt: Any = ...
    txtLogisticsHtVar: Any = ...
    txtLogisticsMTBF: Any = ...
    txtLogisticsMTBFVar: Any = ...
    txtLogisticsRt: Any = ...
    txtLogisticsRtVar: Any = ...
    txtMissionHt: Any = ...
    txtMissionHtVar: Any = ...
    txtMissionMTBF: Any = ...
    txtMissionMTBFVar: Any = ...
    txtMissionRt: Any = ...
    txtMissionRtVar: Any = ...
    txtPercentHt: Any = ...
    txtSoftwareHt: Any = ...
    def __init__(self) -> None: ...

class AvailabilityResultsPanel(RAMSTKPanel):
    txtCostFailure: Any = ...
    txtCostHour: Any = ...
    txtLogisticsAt: Any = ...
    txtLogisticsAtVar: Any = ...
    txtMCMT: Any = ...
    txtMissionAt: Any = ...
    txtMissionAtVar: Any = ...
    txtMMT: Any = ...
    txtMPMT: Any = ...
    txtMTTR: Any = ...
    txtPartCount: Any = ...
    txtTotalCost: Any = ...
    def __init__(self) -> None: ...

class GeneralData(RAMSTKWorkView):
    def __init__(self, configuration: RAMSTKUserConfiguration, logger: RAMSTKLogManager) -> None: ...

class AssessmentInputs(RAMSTKWorkView):
    def __init__(self, configuration: RAMSTKUserConfiguration, logger: RAMSTKLogManager) -> None: ...

class AssessmentResults(RAMSTKWorkView):
    def __init__(self, configuration: RAMSTKUserConfiguration, logger: RAMSTKLogManager) -> None: ...
