# Stubs for ramstk.views.gtk3.revision.listview (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

# RAMSTK Package Imports
from ramstk.views.gtk3.widgets import RAMSTKListView

class FunctionHardware(RAMSTKListView):
    _definition_id: int

    def __init__(self, configuration=configuration, logger=logger,
                 module='') -> None:
        self._definition_id = None
        self._do_request_delete = None
        self.__do_load_tree = None
        self._do_load_tree = None
        ...

    def pack_start(self, param, param1, param2, param3):
        pass

    def __make_buttonbox(self):
        pass

    def __make_treeview(self):
        pass

    def _on_cell_edit(self, __cell: Gtk.CellRenderer, path: str, new_text: str,
                      position: int):
        pass
