# Stubs for ramstk.views.gtk3.revision.listview (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ramstk.configuration import RAMSTKUserConfiguration
from ramstk.logger import RAMSTKLogManager
from ramstk.views.gtk3.widgets import RAMSTKListView

class FailureDefinition(RAMSTKListView):
    _definition_id: int

    def __init__(self, configuration: RAMSTKUserConfiguration, logger: RAMSTKLogManager) -> None:
        self._definition_id = None
        self._do_request_delete = None
        self.__do_load_tree = None
        self._do_load_tree = None
        ...

    def __make_ui(self):
        pass

    def pack_start(self, param, param1, param2, param3):
        pass

    def __make_buttonbox(self):
        pass

    def __make_treeview(self):
        pass

    def _on_cell_edit(self, __cell: Gtk.CellRenderer, path: str, new_text: str,
                      position: int):
        pass

class UsageProfile(RAMSTKListView):
    def __init__(self, configuration: RAMSTKUserConfiguration, logger: RAMSTKLogManager) -> None:
        self._on_cell_edit = None
        self._do_request_delete = None

    def _do_load_tree(self, param: object, row: object) -> object:
        pass

    def __make_ui(self):
        pass

    def __do_load_tree(self, param):
        pass

    def pack_start(self, param, param1, param2, param3):
        pass

    def __make_buttonbox(self):
        pass

    def _do_load_phase(self, _entity, identifier, row):
        pass

    def _do_load_mission(self, _entity, identifier, row):
        pass

    def _do_load_environment(self, _entity, identifier, row):
        pass

    def __make_treeview(self):
        pass

    def __make_cell(self, param, param1, param2):
        pass
