# Stubs for ramstk.views.gtk3.function.moduleview (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

# RAMSTK Package Imports
from ramstk.configuration import RAMSTKUserConfiguration
from ramstk.logger import RAMSTKLogManager
from ramstk.views.gtk3.widgets import RAMSTKModuleView

class ModuleView(RAMSTKModuleView):
    def __init__(self, configuration: RAMSTKUserConfiguration, logger: RAMSTKLogManager, module: Any=...) -> None: ...
