from ramstk.configuration import RAMSTKUserConfiguration as RAMSTKUserConfiguration
from ramstk.logger import RAMSTKLogManager as RAMSTKLogManager
from ramstk.views.gtk3 import Gtk as Gtk
from ramstk.views.gtk3.widgets import RAMSTKCheckButton as RAMSTKCheckButton, RAMSTKEntry as RAMSTKEntry, RAMSTKPanel as RAMSTKPanel, RAMSTKTextView as RAMSTKTextView, RAMSTKWorkView as RAMSTKWorkView
from typing import Any, Dict, List

class GeneralDataPanel(RAMSTKPanel):
    chkSafetyCritical: Any = ...
    txtCode: Any = ...
    txtName: Any = ...
    txtRemarks: Any = ...
    def __init__(self) -> None: ...

class HazOpsPanel(RAMSTKPanel):
    def __init__(self) -> None: ...
    def do_load_criticality(self, criticalities: List[List[str]]) -> None: ...
    def do_load_hazards(self, hazards: Dict[Any, Any]) -> None: ...
    def do_load_probability(self, probabilities: List[str]) -> None: ...

class GeneralData(RAMSTKWorkView):
    def __init__(self, configuration: RAMSTKUserConfiguration, logger: RAMSTKLogManager) -> None: ...

class HazOps(RAMSTKWorkView):
    def __init__(self, configuration: RAMSTKUserConfiguration, logger: RAMSTKLogManager) -> None: ...
