# Standard Library Imports
from typing import Any, Dict, List

# RAMSTK Package Imports
from ramstk.configuration import (
    RAMSTKUserConfiguration as RAMSTKUserConfiguration
)
from ramstk.logger import RAMSTKLogManager as RAMSTKLogManager
from ramstk.views.gtk3 import Gtk as Gtk
from ramstk.views.gtk3.widgets import RAMSTKCheckButton as RAMSTKCheckButton
from ramstk.views.gtk3.widgets import RAMSTKEntry as RAMSTKEntry
from ramstk.views.gtk3.widgets import RAMSTKPanel as RAMSTKPanel
from ramstk.views.gtk3.widgets import RAMSTKTextView as RAMSTKTextView
from ramstk.views.gtk3.widgets import RAMSTKWorkView as RAMSTKWorkView

class GeneralDataPanel(RAMSTKPanel):
    chkSafetyCritical: Any = ...
    txtCode: Any = ...
    txtName: Any = ...
    txtRemarks: Any = ...
    def __init__(self) -> None: ...

class HazOpsPanel(RAMSTKPanel):
    def __init__(self) -> None: ...
    def do_load_criticality(self, criticalities: List[List[str]]) -> None: ...
    def do_load_hazards(self, hazards: Dict[Any, Any]) -> None: ...
    def do_load_probability(self, probabilities: List[str]) -> None: ...
    def do_set_callbacks(self) -> None: ...

class GeneralData(RAMSTKWorkView):
    def __init__(self, configuration: RAMSTKUserConfiguration, logger: RAMSTKLogManager) -> None: ...

class HazOps(RAMSTKWorkView):
    def __init__(self, configuration: RAMSTKUserConfiguration, logger: RAMSTKLogManager) -> None: ...
