# Standard Library Imports
from typing import Any

# RAMSTK Package Imports
from ramstk.controllers import RAMSTKDataManager as RAMSTKDataManager
from ramstk.db.base import BaseDatabase as BaseDatabase
from ramstk.models.programdb import RAMSTKProgramInfo as RAMSTKProgramInfo

class DataManager(RAMSTKDataManager):
    _db_id_colname: str = ...
    _db_tablename: str = ...
    _tag: str = ...
    _pkey: Any = ...
    def __init__(self, **kwargs: Any) -> None: ...
    dao: Any = ...
    def _do_select_all(self, dao: BaseDatabase) -> None: ...
