name: Update CHANGELOG.md

on:
  pull_request:
    types: [closed]

jobs:
  generate_change_log:
    name: Generate and push a CHANGELOG.md
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate CHANGELOG.md
        uses: charmixer/auto-changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit CHANGELOG.md
        env:
          CI_USER: ${{ secrets.CI_USER }}
          CI_EMAIL: ${{ secrets.CI_EMAIL }}
        run: |
          git config --local user.email "$CI_EMAIL"
          git config --local user.name "$CI_USER"
          git add CHANGELOG.md && git commit -m "Updated CHANGELOG.md" && echo ::set-env name=push::1 || echo "No changes to CHANGELOG.md"

      - name: Push CHANGELOG.md
        if: env.push == 1
        env:
          CI_USER: ${{ secrets.CI_USER }}
          CI_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push "https://$CI_USER:$CI_TOKEN@github.com/$GITHUB_REPOSITORY.git" HEAD:develop
