name: Pull Request Chores

on:
  pull_request:
    branches:
      - master

jobs:
  pr-labeler:
    name: Label Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Apply labels to PR
        uses: TimonVS/pr-labeler-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create_new_milestone:
    name: Create New Milestone
    runs-on: ubuntu-latest
    steps:

      - name: Check for major/minor PR labels
        id: check_pr_labels
        uses: shioyang/check-pr-labels-on-push-action@v1.0.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labels: '["major", "minor"]'

      - name: Update draft release
        id: draft_release
        if: ${{ steps.check_pr_labels.outputs.result == 'true' }}
        uses: release-drafter/release-drafter@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create new milestone
        if: ${{ steps.check_pr_labels.outputs.result == 'true' }}
        uses: WyriHaximus/github-action-create-milestone@master
        with:
          title: "${{ steps.draft_release.outputs.tag_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for major/minor/patch PR labels
        id: check_pr_labels_all
        uses: shioyang/check-pr-labels-on-push-action@v1.0.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labels: '["major", "minor", "patch"]'
      - name: See results
        run: |
          echo ${{ steps.check_pr_labels_all.outputs.result }}
          echo ${{ steps.draft_release.outputs.name }}

      - name: Update VERSION and pyproject.toml file
        if: ${{ steps.check_pr_labels_all.outputs.result == 'true' }}
        run: |
          echo "${{ steps.draft_release.outputs.name }}" > VERSION
          sed -i 's/\(^version =.*$\)/version = "${{ steps.draft_release.outputs.name }}"/' pyproject.toml
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -a -m "Update VERSION and pyproject.toml" && echo "do_push=1" >> $GITHUB_ENV

      - name: Update PR
        if: ${{ env.do_push == 1 }}
        uses: peter-evans/create-pull-request@v3
        with:
          branch: ${{ env.GITHUB_REF }}
