name: Pull Request QA

on:
  pull_request:
    branches:
      - master

jobs:
  good_pr_title:
    name: Ensure Conventional PR Title
    runs-on: ubuntu-latest
    steps:
      - name: Ensure PR title follows conventional commits specification
        uses: aslafy-z/conventional-pr-title-action@master
        with:
          success-state: Conventional commits compliant title detected.
          failure-state: Pull request title is not conventional commits compliant!
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  pr-labeler:
    name: Label pull request
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  update_release_draft:
    name: Update draft release
    runs-on: ubuntu-latest
    steps:
      - name: Determine Next Version
        id: version
        uses: patrickjahns/version-drafter-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: release-drafter/release-drafter@master
        with:
          version: ${{ format('v{0}', steps.version.outputs.next-version) }}
          tag: ${{ format('v{0}', steps.version.outputs.next-version) }}
          name: ${{ format('v{0}', steps.version.outputs.next-version) }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
