name: Pull Request Chores

on:
  pull_request:
    branches:
      - master

jobs:
  create_new_milestone:
    name: Create New Milestone
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0

      - name: Get PR labels
        id: check_pr_labels
        uses: joerick/pr-labels-action@v1.0.6

      - name: Get Previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get next semantic version
        id: nexttag
        uses: WyriHaximus/github-action-next-semvers@v1
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - name: See results
        run: |
          echo ${{ steps.previoustag.outputs.tag }}
          echo ${{ steps.check_pr_labels.outputs.labels }}
          echo ${{ steps.nexttag.outputs.v_major }}
          echo ${{ steps.nexttag.outputs.v_minor }}
          echo ${{ steps.nexttag.outputs.v_patch }}

      - name: Create new major release milestone
        if: contains(steps.check_pr_labels.outputs.labels, ' major ')
        uses: WyriHaximus/github-action-create-milestone@master
        with:
          title: "${{ steps.nexttag.outputs.v_major }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create new minor release milestone
        if: contains(steps.check_pr_labels.outputs.labels, ' minor ')
        uses: WyriHaximus/github-action-create-milestone@master
        with:
          title: "${{ steps.nexttag.outputs.v_minor }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
