name: Create New Milestone

on:
  pull_request:
    branches:
      - master

jobs:
  create_new_milestone:
    name: Create New Milestone
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0

      - name: Get PR labels
        id: check_pr_labels
        uses: joerick/pr-labels-action@v1.0.6

      - name: Get previous tag
        id: previoustag
        run: |
          echo "::set-output name=tag::$(git describe $(git rev-list --tags --max-count=1 --skip=1) | cut -d '-' -f1 | cut -d 'v' -f2)"

      - name: Get next semantic version
        id: nexttag
        uses: WyriHaximus/github-action-next-semvers@v1
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - name: See results
        run: |
          echo ${{ steps.previoustag.outputs.tag }}
          echo ${{ steps.check_pr_labels.outputs.labels }}
          echo ${{ steps.nexttag.outputs.v_major }}
          echo ${{ steps.nexttag.outputs.v_minor }}
          echo ${{ steps.nexttag.outputs.v_patch }}

      - name: Check for new minor version
        if: contains(steps.check_pr_labels.outputs.labels, ' minor ')
        run: |
          echo "RAMSTK_NEXT_VER=${{ steps.nexttag.outputs.minor }}" >> $GITHUB_ENV
          echo "do_milestone=1" >> $GITHUB_ENV

      - name: Check for new major version
        if: contains(steps.check_pr_labels.outputs.labels, ' major ')
        run: |
          echo "RAMSTK_NEXT_VER=${{ steps.nexttag.outputs.major }}" >> $GITHUB_ENV
          echo "do_milestone=1" >> $GITHUB_ENV

      - name: Create new release milestone
        if: ${{ env.do_milestone == 1 }}
        uses: WyriHaximus/github-action-create-milestone@master
        with:
          title: "v${{ env.RAMSTK_NEXT_VER }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
