name: Cut Tagged Release

on:
  push:
    tags:
      - "v*"

jobs:
  tagged_release:
    name: Release Tagged Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
