name: Develop Branch Workflow

on:
  push:
    branches: develop

jobs:
  codacy_coverage_reporter:
    name: Report Coverage to Codacy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: cobertura.xml

  todo_issue:
    name: Create Issues from Todos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
      - name: TODO to Issue
        id: todo
        uses: alstr/todo-to-issue-action@v2.0
        with:
          REPO: ${{ github.repository }}
          BEFORE: ${{ github.event.before }}
          SHA: ${{ github.sha }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABEL: "#// TODO:"
          COMMENT_MARKER: "#//"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update_release_draft:
    name: Update the Draft Release
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_documentation:
    name: Update API documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"

      - name: Commit API Documentation
        run: |
          git clone https://github.com/ReliaQualAssociates/ramstk.git --branch gh-pages --single-branch gh-pages
          cp -r docs/_build/html/* gh-pages/
          cd gh-pages
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -a -m "Update documentation"

      - name: Push Documentation Changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
