# This workflow runs when a push is made or a PR is opened, reopened, or synchronized.
#
# - Job 1:
#     - Run bandit against the entire code base.
# - Job 2:
#     - Run black, isort, and docformatter against the entire code base.
# - Job 3:
#     - Run pycodestyle and pydocstyle against the entire code base.
# - Job 4:
#     - Run mypy agaisnt the entire code base.
# - Job 5:
#     - Run pylint and flake8 (future) against the entire code base.
name: Perform Static Checks on RAMSTK Code Base

on:
  push:
    branches:
      - 'master'
      - 'dependabot'
      - '!release/**'
      - '!chore/**'
      - '!docs/**'
    paths:
      - "**.py"
    tags-ignore:
      - "*"
  pull_request:
    paths:
      - "**.py"
    types:
      - "opened"
      - "reopened"
      - "synchronize"

jobs:
  bandit:
    name: Check for Security Vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run bandit against repository
        uses: jpetrucciani/bandit-check@master
        with:
          path: 'src/ramstk'

  format-check:
    name: Check Code Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check code format with black, isort, and docformatter
        uses: weibullguy/python-lint-plus@master
        with:
          python-root-list: "src/ramstk"
          use-black: true
          use-isort: true
          use-docformatter: true
          extra-black-options: "--config ./pyproject.toml"
          extra-isort-options: "--settings-file ./pyproject.toml"
          extra-docformatter-options: "--config ./pyproject.toml"

  style-check:
    name: Check Code Styling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check code style with pycodestyle and pydocstyle
        uses: weibullguy/python-lint-plus@master
        with:
          python-root-list: "src/ramstk"
          use-pycodestyle: true
          use-pydocstyle: true
          extra-pycodestyle-options: "--config=./setup.cfg --count"
          extra-pydocstyle-options: "--count"

  type-check:
    name: Check Code Type Hinting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check code type hinting with mypy
        uses: weibullguy/python-lint-plus@master
        with:
          python-root-list: "src/ramstk"
          use-mypy: true
          extra-mypy-options: "--config-file ./pyproject.toml"

  lint-check:
    name: Check Code Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint code with pylint
        uses: weibullguy/python-lint-plus@master
        with:
          python-root-list: "src/ramstk"
          use-pylint: true
          extra-pylint-options: "-j0 --rcfile=./pyproject.toml"
