name: Execute RAMSTK Test Suite with Coverage

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags-ignore:
      - "*"

jobs:
  test_suite:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ 3.6, 3.7, 3.8 ]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update and install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends apt-utils git libgirepository1.0-dev gir1.2-gtk-3.0 python3-gi python3-gi-cairo python3-pytest libenchant1c2a libenchant-dev python3-numpy python3-scipy xauth xvfb

      - name: Set up Python ${{ matrix.python }}
        id: setpy
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Create a virtual environment
        needs: setpy
        id: venv
        run: |
          echo "VIRTUAL_ENV=ramstk-venv${{ matrix.python }}" >> $GITHUB_ENV
          python -mvenv $VIRTUAL_ENV

      - name: Install RAMSTK dependencies
        needs: venv
        id: deps
        run: |
          source $VIRTUAL_ENV/bin/activate
          pip install -U pip setuptools>12.0 urllib3 poetry importlib_metadata
          python poetry_fix.py
          make depends

      - name: Install RAMSTK and test with coverage
        needs: deps
        id: test
        run: |
          make PREFIX=$VIRTUAL_ENV install
          xvfb-run --auto-servernum make coverage

      - name: Upload coverage to Codecov
        needs: test
        uses: codecov/codecov-action@v1
        with:
          files: ./cobertura.xml
          flags: ${{ matrix.python }}

      - name: Create Coveralls report
        needs: test
        uses: miurahr/coveralls-python-action@patch-pyprject-toml
        with:
          parallel: true

  upload_coveralls:
    needs: test_suite
    runs-on: ubuntu-latest
    steps:
      - name: Upload coverage report to Coveralls
        uses: miurahr/coveralls-python-action@patch-pyprject-toml
        with:
          parallel-finished: true
