name: Draft Release

on:
  push:
    branches:
      - master

jobs:
  update_release_draft:
    name: Draft a Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get PR labels
        id: check_pr_labels
        uses: shioyang/check-pr-labels-on-push-action@v1.0.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labels: '["major", "minor", "patch"]'

      - name: Draft release notes
        id: draft_release
        uses: release-drafter/release-drafter@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update VERSION and pyproject.toml file
        if: ${{ steps.check_pr_labels.outputs.result }}
        run: |
          echo "${{ steps.draft_release.outputs.name }}" > VERSION
          sed -i 's/\(^version =.*$\)/version = "${{ steps.draft_release.outputs.name }}"/' pyproject.toml
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -a -m "Update VERSION and pyproject.toml" && echo "do_push=1" >> $GITHUB_ENV

      - name: Get PR labels
        id: check_pr_labels_again
        uses: shioyang/check-pr-labels-on-push-action@v1.0.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labels: '["major", "minor"]'

      - name: Update CHANGELOG.md and cut release PR
        if: ${{ steps.check_pr_labels.outputs.result }}
        uses: patrickjahns/chlgr@v1
        with:
          release-version: ${{ steps.draft_release.outputs.tag_name }}
          release-branch: "release/${{ steps.draft_release.outputs.tag_name }}"
