name: Pull Request Chores

on:
  pull_request:
    types: [opened]

jobs:
  pr-labeler:
    name: Label Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Apply labels to PR
        uses: TimonVS/pr-labeler-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
