name: Master Branch Workflow

on:
  push:
    branches: master

jobs:
  tag_with_milestone:
    name: Tag and Create New Milestone
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump Version and Push Tag
        id: bumpver
        uses: mathieudutour/github-tag-action@v4
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: minor
          release_branches: release
          create_annotated_tag: true
      - name: Get Next Minor Version
        id: semvers
        uses: WyriHaximus/github-action-next-semvers@master
        with:
          version: ${{ steps.bumpver.outputs.new_tag }}
      - name: Create New Milestone
        id: newmilestone
        uses: WyriHaximus/github-action-create-milestone@master
        with:
          title: ${{ steps.semvers.outputs.v_minor }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
