name: Move New Issues into Triage

on:
  issues:
    types: [opened]

jobs:
  assign_issues_to_project:
    name: Assign New Issue to Project
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/create-project-card-action@v1
        with:
          PROJECT: Backlog
          COLUMN: Triage
