name: Issue Assigned Workflow
on:
  issues:
    types: [assigned]

jobs:
  create_issue_branch_job:
    name: Create Branch for Issue
    runs-on: ubuntu-latest
    steps:
      - name: Is Issue dobranch
        id: getlabel
        uses: renanmav/match-label-action@v3
        with:
          allowed: >
            dobranch
            Release
      - name: Create Issue Branch
        id: create_issue_branch
        if: steps.getlabel.outputs.match == 'dobranch'
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  label_issue_in_progress:
    runs-on: ubuntu-latest
    steps:
      - name: Add In Progress Label
        uses: andymckay/labeler@master
        with:
          add-labels: "status: inprogress"
          remove-labels: "status: backlog"
