name: Assigned Issue Workflow
on:
  issues:
    types: [assigned]
  issue_comment:
    types: [created]

jobs:
  create_issue_branch_job:
    name: Create Branch for Issue
    runs-on: ubuntu-latest
    steps:
      - name: Is Issue Epic
        id: getlabel
        uses: renanmav/match-label-action@v3
        with:
          allowed: >
            dobranch
      - name: Create Issue Branch
        id: create_issue_branch
        if: steps.getlabel.outputs.match == "dobranch"
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
