# This workflow runs when a PR is merged to the master branch.
#
# - Job 1:
#     - Imports signing GPG key.
#     - Signs and pushes 'latest' tag.  This happens on every push to master.
#     - Updates draft release notes.  This happens on every push to master.
name: Merge Pull Request Workflow

on:
  push:
    branches:
      - master
    tags-ignore:
      - "*"

jobs:
  tag-latest:
    name: Tag Repository as 'latest'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Push 'latest' tag
        run: |
          git config --global user.email "${{ steps.import_gpg.outputs.email }}"
          git config --global user.name "${{ steps.import_gpg.outputs.name }}"
          git tag -s -f -a -m"push latest tag" latest
          git push -f --tags

      - name: Draft 'latest' release notes
        uses: release-drafter/release-drafter@master
        with:
          name: "Next Release"
          tag: "latest"
          version: "latest"
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
