name: Project Card Moved Workflow

on:
  project_card:
    types: [moved]

jobs:
  cal:
    name: Label Issues and PR on Move
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/auto-card-labeler@v2
