name: PR Merge Workflow

on:
  push:
    branches:
      - master
    tags-ignore:
      - "*"

jobs:
  pre_release:
    name: Create Development Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push 'latest' tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -f -a -m"push latest tag" latest
          git push -f --tags

      - name: Draft 'latest' release notes
        uses: release-drafter/release-drafter@master
        with:
          name: "Next Release"
          tag: "latest"
          version: "latest"
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  todo_issue:
    name: Create Issues from TODOs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: TODO to Issue
        id: todo
        uses: alstr/todo-to-issue-action@master
        with:
          REPO: ${{ github.repository }}
          BEFORE: ${{ github.event.before }}
          SHA: ${{ github.sha }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABEL: "# ISSUE:"
          COMMENT_MARKER: "#"
          AUTO_P: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
