# This workflow runs when a PR is merged to the master branch.
#
# - Job 1:
#     - Imports signing GPG key.
#     - Signs and pushes 'latest' tag.  This happens on every push to master.
#     - Updates draft release notes.  This happens on every push to master.
name: Merge Pull Request Workflow

on:
  push:
    branches:
      - master
    tags-ignore:
      - "*"

jobs:
  build_documentation:
    name: Build RAMSTK Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Execute Sphinx
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Commit RAMSTK Documentation Changes
        run: |
          git clone https://github.com/ReliaQualAssociates/ramstk.git --branch gh-pages --single-branch gh-pages
          cp -fvr docs/_build/html/* gh-pages/
          cd gh-pages
          git config --local user.email "${{ steps.import_gpg.outputs.email }}"
          git config --local user.name "${{ steps.import_gpg.outputs.name }}"
          git add .
          git commit -a -m "Update documentation" && echo "do_push=1" >> $GITHUB_ENV || echo "Nothing to commit, working tree clean."

      - name: Push RAMSTK Documentation Changes
        if: env.do_push == 1
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
