name: PR Merge Workflow

on:
  push:
    branches:
      - master
    tags-ignore:
      - "*"

jobs:
  test_suite:
    name: RAMSTK Test Suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2

      - name: Update and install system packages
        run: |
          echo "VIRTUAL_ENV=ramstk-venv${{ matrix.python }}" >> $GITHUB_ENV
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends apt-utils git libgirepository1.0-dev gir1.2-gtk-3.0 python3-gi python3-gi-cairo python3-pytest libenchant1c2a libenchant-dev python3-numpy python3-scipy xauth xvfb

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Create a virtual environment
        run: |
          python -mvenv $VIRTUAL_ENV

      - name: Install RAMSTK dependencies and test with coverage
        run: |
          source $VIRTUAL_ENV/bin/activate
          pip install -U pip setuptools>12.0 urllib3 poetry
          make depends
          make PREFIX=$VIRTUAL_ENV install
          xvfb-run --auto-servernum make coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          files: ./cobertura.xml
          flags: ${{ matrix.python }}

      - name: Create Coveralls report
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel: true

  upload_coveralls:
    name: Upload Coverage Results to Coveralls
    needs: test_suite
    runs-on: ubuntu-latest
    steps:
      - name: Upload report to Coveralls
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel-finished: true

  build_documentation:
    name: Build RAMSTK documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"

      - name: Commit RAMSTK Documentation
        run: |
          git clone https://github.com/ReliaQualAssociates/ramstk.git --branch gh-pages --single-branch gh-pages
          cp -fr docs/_build/html/* gh-pages/
          cd gh-pages
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -a -m "Update documentation" && echo "do_push=1" >> $GITHUB_ENV || echo "Nothing to commit, working tree clean."

      - name: Push RAMSTK Documentation Changes
        if: env.do_push == 1
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}

  pre_release:
    name: Tag and Draft 'latest' Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push 'latest' tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -f -a -m"push latest tag" latest
          git push -f --tags

      - name: Draft 'latest' release notes
        uses: release-drafter/release-drafter@master
        with:
          name: "latest"
          tag: "latest"
          version: "latest"
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  tag_master:
    name: Tag and Draft Versioned Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get version information
        id: versions
        run: |
          tag_ver=$(git describe $(git rev-list --tags --max-count=1 --skip=1) | cut -d '-' -f1 | cut -d 'v' -f2)
          file_ver=$(cat VERSION)

          tag_ver=$(echo $tag_ver | cut -d 'v' -f2)
          tag_major=$(echo $tag_ver | cut -d '.' -f1)
          tag_minor=$(echo $tag_ver | cut -d '.' -f2)
          tag_patch=$(echo $tag_ver | cut -d '.' -f3)

          file_major=$(echo $file_ver | cut -d '.' -f1)
          file_minor=$(echo $file_ver | cut -d '.' -f2)
          file_patch=$(echo $file_ver | cut -d '.' -f3)

          echo "Tag: $tag_ver"
          echo "VERSION: $file_ver"
          echo "Tag major: $tag_major"
          echo "Tag minor: $tag_minor"
          echo "Tag patch: $tag_patch"
          echo "File major: $file_major"
          echo "File minor: $file_minor"
          echo "File patch: $file_patch"

          echo "::set-output name=new_ver::$(echo $file_ver)"

          if [[ $file_major > $tag_major ]] || [[ $file_minor > $tag_minor ]]; then echo "do_release=1" >> $GITHUB_ENV; fi
          if [[ $file_major > $tag_major ]] || [[ $file_minor > $tag_minor ]] || [[ $file_patch > $tag_patch ]]; then echo "do_tag=1" >> $GITHUB_ENV; fi

      - name: Check
        run: |
          echo "${{ steps.versions.outputs.new_ver }}"
          echo "${{ env.do_release }}"
          echo "${{ env.do_tag }}"

      - name: Push versioned tag
        if: ${{ env.do_tag == 1 }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a -m"v${{ steps.versions.outputs.new_ver }}" v${{ steps.versions.outputs.new_ver }}
          git push --tags

      - name: Draft versioned release notes
        if: ${{ env.do_release == 1}}
        uses: release-drafter/release-drafter@master
        with:
          name: "v${{ steps.versions.new_ver }}"
          tag: "v${{ steps.versions.new_ver }}"
          version: "v${{ steps.versions.new_ver }}"
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  todo_issue:
    name: Create Issues from TODOs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: TODO to Issue
        id: todo
        uses: alstr/todo-to-issue-action@v2.0
        with:
          REPO: ${{ github.repository }}
          BEFORE: ${{ github.event.before }}
          SHA: ${{ github.sha }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABEL: "# ISSUE:"
          COMMENT_MARKER: "#"
          AUTO_P: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
