# This workflow runs when a push is made to the master branch.
#
# - Job 1:
#     - Create new minor version milestone.
#     - Create new major version milestone.
# - Job 2:
#     - Build RAMSTK documentation.
#     - Publish RAMSTK documentation.

name: Publish Release Workflow

on:
  release:
    types:
      - published

jobs:
  create_new_milestone:
    name: Create New Milestone
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0

      - name: Get new version
        id: newversion
        run: |
          echo "::set-output name=version::$(echo $(cat VERSION))"

      - name: Get next semantic version
        id: nextversion
        uses: WyriHaximus/github-action-next-semvers@v1.1.0
        with:
          version: ${{ steps.newversion.outputs.version }}

      - name: Create new minor release milestone
        uses: WyriHaximus/github-action-create-milestone@master
        with:
          title: "${{ steps.nextversion.outputs.v_minor }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create new major release milestone
        uses: WyriHaximus/github-action-create-milestone@master
        with:
          title: "${{ steps.nextversion.outputs.v_major }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_documentation:
    name: Build RAMSTK Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Execute Sphinx
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"

      - name: Commit RAMSTK Documentation Changes
        run: |
          git clone https://github.com/ReliaQualAssociates/ramstk.git --branch gh-pages --single-branch gh-pages
          cp -fr docs/_build/html/* gh-pages/
          cd gh-pages
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -a -m "Update documentation" && echo "do_push=1" >> $GITHUB_ENV || echo "Nothing to commit, working tree clean."

      - name: Push RAMSTK Documentation Changes
        if: env.do_push == 1
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
