name: Create Pre-Release and Tag

on:
  push:
    branches:
      - master
    tags-ignore:
      - "*"

jobs:
  pre_release:
    name: Tag and Draft 'latest' Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push 'latest' tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -f -a -m"push latest tag" latest
          git push -f --tags

      - name: Draft 'latest' release notes
        uses: release-drafter/release-drafter@master
        with:
          name: "latest"
          tag: "latest"
          version: "latest"
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  tag_master:
    name: Tag and Draft Versioned Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get version information
        id: versions
        run: |
          tag_ver=$(git describe --abbrev=0 --tags)
          file_ver=$(cat VERSION)

          tag_ver=$(echo $tag_ver | cut -d 'v' -f2)
          tag_major=$(echo $tag_ver | cut -d '.' -f1)
          tag_minor=$(echo $tag_ver | cut -d '.' -f2)
          tag_patch=$(echo $tag_ver | cut -d '.' -f3)

          file_major=$(echo $tag_ver | cut -d '.' -f1)
          file_minor=$(echo $tag_ver | cut -d '.' -f2)
          file_patch=$(echo $tag_ver | cut -d '.' -f3)
          
          echo "Tag: $tag_ver"
          echo "VERSION: $file_ver"
          echo "Tag major: $tag_major"
          echo "Tag minor: $tag_minor"
          echo "Tag patch: $tag_patch"
          echo "File major: $file_major"
          echo "File minor: $file_minor"
          echo "File patch: $file_patch"
          
          echo "::set-output name=new_ver::$(echo $file_ver)"

          if [[ $file_major > $tag_major ]] || [[ $file_minor > $tag_minor ]]; then echo "do_release=1" >> $GITHUB_ENV; fi
          if [[ $file_major > $tag_major ]] || [[ $file_minor > $tag_minor ]] || [[ $file_patch > $tag_patch ]]; then echo "do_tag=1" >> $GITHUB_ENV; fi

      - name: Check
        run: |
          echo "${{ steps.versions.outputs.new_ver }}"
          echo "${{ env.do_release }}"
          echo "${{ env.do_tag }}"
          
      - name: Push versioned tag
        if: ${{ env.do_tag == 1 }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a -m"v${{ steps.versions.outputs.new_ver }}" v${{ steps.versions.outputs.new_ver }}
          git push --tags

      - name: Draft versioned release notes
        if: ${{ env.do_release == 1}}
        uses: release-drafter/release-drafter@master
        with:
          name: "v${{ steps.versions.new_ver }}"
          tag: "v${{ steps.versions.new_ver }}"
          version: "v${{ steps.versions.new_ver }}"
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
