name: Pull Request QA Workflow

on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  checklist:
    name: Add Pull Request Checklist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: wyozi/contextual-qa-checklist-action@master
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          input-file: devtools/CHECKLIST.yml

  labeler:
    name: Label the Pull Request Size
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: codelytv/pr-size-labeler@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_max_size: '10'
          s_max_size: '100'
          m_max_size: '500'
          l_max_size: '1000'
          fail_if_xl: 'false'

  check_for_changelog:
    name: Check for CHANGELOG
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: peterjgrainger/action-changelog-reminder@v1.2.0
        with:
          changelog_regex: 'CHANGELOG.md'
          customPrMessage: 'Remember to add a CHANGELOG'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release_notes_preview:
    name: Preview Release Notes
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow --tags
      - uses: snyk/release-notes-preview@v1.6.1
        with:
          releaseBranch: develop
        env:
          GITHUB_PR_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  semver_release:
    name: Semantic Versioned Release
    runs-on: ubunu-latest
    steps:
      - name: Release
        id: next_version
        uses: ridedott/release-me-action@master
        with:
          dry-run: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: results
        id: semver
        run: echo "${{ steps.next_version.outputs.version }}"
        run: echo "${{ steps.next_version.outputs.level }}"
