name: Pull Request QA Workflow

on:
  pull_request:
    branches:
      - develop
      - master
    types:
      - opened
      - edited
      - synchronize

jobs:
  good_pr_title:
    name: Ensure Sematic PR Title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  bandit:
    name: Check for Security Vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run bandit against repository
        uses: jpetrucciani/bandit-check@master
        with:
          path: 'src/ramstk'

  lint-it:
    name: Lint Code and Style Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Lint files using pylint, pycodestyle, mypy, and isort
        uses: ricardochaves/python-lint@v1.1.0
        with:
          python-root-list: "src/ramstk"
          use-pylint: true
          use-pycodestyle: true
          use-mypy: true
          use-isort: true
          extra-pylint-options: "-j0 --rcfile=./.pylintrc --dummy-variables-rgx='__'"
          extra-pycodestyle-options: "--statistics --count"
          extra-mypy-options: ""
          extra-isort-options: "--use-parentheses --balanced --multi-line 5"

  yapf-it:
    name: Check Code Formatting with YAPF
    runs-on: ununtu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run YAPF against changed files
        uses: AlexanderMelde/yapf-action@master
        with:
          args: --exclude '**/tests/**'
