on: push
jobs:
  build:
    name: Coveralls GitHub Action
    runs-on: ubuntu-latest
    steps:
    - uses: coverallsapp/github-action@v1.0.1
      with:
        github-token: ${{ secrets.GithubToken }}
