name: Pull Request QA Workflow

on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  generate_changelog:
    name: Generate a Changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
      - uses: etcdigital/pull-request-changelog@1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  check_for_changelog:
    name: Ensure CHANGELOG Exists
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
      - name: CHANGELOG Reminder
        uses: peterjgrainger/action-changelog-reminder@v1.2.0
        with:
          changelog_regex: 'CHANGELOG.md'
          customPrMessage: 'Remember to add a CHANGELOG'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release_notes_preview:
    name: Preview Release Notes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
      - run: git fetch --prune --tags
      - name: Release Notes Preview
        uses: snyk/release-notes-preview@v1.6.1
        with:
          releaseBranch: develop
        env:
          GITHUB_PR_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  todo_issue:
    name: Create Issues from Todos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
      - name: TODO to Issue
        id: todo
        uses: alstr/todo-to-issue-action@master
        with:
          REPO: ${{ github.repository }}
          BEFORE: ${{ github.event.before }}
          SHA: ${{ github.sha }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABEL: "#// TODO:"
          COMMENT_MARKER: "#//"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Tag and Create New Milestone
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump Version and Push Tag
        id: bumpver
        uses: mathieudutour/github-tag-action@v4
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: minor
          release_branches: release
          create_annotated_tag: true
      - name: Get Next Minor Version
        id: semvers
        uses: WyriHaximus/github-action-next-semvers@master
        with:
          version: ${{ steps.bumpver.outputs.new_tag }}
      - name: Create New Milestone
        id: newmilestone
        uses: WyriHaximus/github-action-create-milestone@master
        with:
          title: ${{ steps.semvers.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
