name: Push Workflows
on:
  push:
    branches:
      - develop
      - master
jobs:
  codacy-coverage-reporter:
    name: Codacy Coverage Report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run codacy-coverage-reporter
        uses: mrfyda/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
