name: Release Workflow

on:
  pull_request:
    branches: [ master ]
  issue_comment:
    types: [ edited ]

jobs:
  release_notes_preview:
    name: Release Notes Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: snyk/release-notes-preview@v1.6.2
        with:
          releaseBranch: master
        env:
          GITHUB_PR_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  bump_semantic_version:
    name: Bump Semantic Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: current_version
        uses: zwaldowski/match-label-action@v1
        with:
          allowed: major, minor, patch
      - run: echo ${{ steps.current_version.match }}
      - id: bsv
        uses: zwaldowski/semver-release-action@v1
        with:
          bump: ${{ steps.current_version.match }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
