name: Release Workflow

on:
  pull_request:
    branches: release/*

jobs:
  release_notes_preview:
    name: Preview Release Notes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
      - run: git fetch --prune --tags
      - name: Release Notes Preview
        uses: snyk/release-notes-preview@v1.6.1
        with:
          releaseBranch: develop
        env:
          GITHUB_PR_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  bump_semantic_version:
    name: Bump Semantic Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: lrb
        uses: jessicalostinspace/github-action-get-regex-branch@v1.0.8
        with:
          regex-string: 'release'
      - id: current_version
        uses: zwaldowski/match-label-action@v1
        with:
          allowed: MAJOR, MINOR, PATCH
        run: echo ${{ steps.current_version.match }}
      - id: bsv
        uses: jessicalostinspace/bump-semantic-version-action@v1.0.1
        with:
          semantic-version: ${{ steps.lrb.outputs.last-semver }}
          version-type: ${{ steps.current_version.match }}
