name: Release Workflow

on:
  pull_request:
    branches: release*

jobs:
  release_notes_preview:
    name: Preview Release Notes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
      - run: git fetch --prune --tags
      - name: Release Notes Preview
        uses: snyk/release-notes-preview@v1.6.1
        with:
          releaseBranch: develop
        env:
          GITHUB_PR_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
