name: Run RAMSTK Test Suite

on:
  pull_request:
    branches:
      - master

jobs:
  runner-job:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends apt-utils git libgirepository1.0-dev gir1.2-gtk-3.0 python3-gi python3-gi-cairo python3-pytest libenchant1c2a libenchant-dev python3-numpy python3-scipy xauth xvfb
          pip install -U pip setuptools>12.0 urllib3 pip-tools
          pip install -U -r requirements.txt -r requirements-test.txt

      - name: Install RAMSTK
        run: make install

      - name: Run tests with coverage
        run: make coverage
