name: Run RAMSTK Test Suite

on:
  pull_request:
    branches:
      - master

jobs:
  test_suite:
    name: RAMSTK Test Suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.6, 3.7]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2

      - name: Update and install system packages
        run: |
          echo "VIRTUAL_ENV=ramstk-venv${{ matrix.python }}" >> $GITHUB_ENV
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends apt-utils git libgirepository1.0-dev gir1.2-gtk-3.0 python3-gi python3-gi-cairo python3-pytest libenchant1c2a libenchant-dev python3-numpy python3-scipy xauth xvfb

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Create a virtual environment
        run: |
          python -mvenv $VIRTUAL_ENV

      - name: Install and test RAMSTK
        run: |
          source $VIRTUAL_ENV/bin/activate
          pip install -U pip setuptools>12.0 urllib3 pip-tools
          pip install -U -r requirements.txt -r requirements-test.txt
          make PREFIX=$VIRTUAL_ENV install
          xvfb-run --auto-servernum make coverage
