name: Bump Version

on:
  pull_request:
    branches:
      - release/v*

jobs:
  bump_semantic_version:
    name: Bump Semantic Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Determine next implied version
        id: nextversion
        uses: paulhatch/semantic-version@v3.2
        with:
          branch: "develop"
          format: "${major}.${minor}.${patch}-rc${increment}"
          short_tags: false
      - name: Output new version
        run: |
          echo "Major: ${{ steps.nextversion.outputs.major }}"
          echo "Minor: ${{ steps.nextversion.outputs.minor }}"
          echo "Patch: ${{ steps.nextversion.outputs.patch }}"
          echo "Increment: ${{ steps.nextversion.outputs.increment }}"
          echo "Version: ${{ steps.nextversion.outputs.version }}"
          echo "Version Tag: ${{ steps.nextversion.outputs.version_tag }}"
          echo "Changed: ${{ steps.nextversion.outputs.changed }}"
      - name: Bump release version
        id: bumpversion
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: "${{ steps.nextversion.outputs.version }}"
          version-fragment: "rc"
      - name: Output next version
        run: |
          echo "Next Version: ${{ steps.bumpversion.outputs.next-version }}"
      - name: Version release
        id: nextversion2
        uses: zwaldowski/semver-release-action@v1
        with:
          dry_run: true
          bump: prerelease
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Output next version 2
        run: |
          echo "Next Version 2: ${{ steps.nextversion2.version }}"
          echo "Optimistic Version 2: ${{ steps.nextversion2.version_optimistic }}"
          echo "Version Tag 2: ${{ steps.nextversion2.version_tag }}"
