name: Bump Version, Tag, and Cut Release PR

on:
  push:
    branches:
      - master

jobs:
  bump_semantic_version:
    name: Bump Semantic Version & Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Bump version, tag, and generate CHANGELOG.md
        id: bumpver
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version-file: pyproject.toml
          version-path: 'project.version'
          fallback-version: ${{ steps.previoustag.outputs.tag }}
          skip-commit: true

      - name: Update VERSION file
        if: ${{ steps.bumpver.outputs.skipped == 'false' }}
        run: |
          echo "${{ steps.bumpver.outputs.version }} > VERSION
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -a -m "Update VERSION" && echo "do_push=1" >> $GITHUB_ENV

      - name: Cut release PR
        if: ${{ steps.bumpver.outputs.skipped == 'false' }}
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: prepare for release ${{ steps.bumpver.outputs.tag }}
          title: Release ${{ steps.bumpver.outputs.tag }}
          body: Update VERSION, pyproject.toml, CHANGELOG.md in preparation for release
          branch: release/${{ steps.bumpver.outputs.tag }}

      - name: Create new milestone
        id: createmilestone
        if: ${{ steps.bumpver.outputs.skipped == 'false' }}
        uses: WyriHaximus/github-action-create-milestone@master
        with:
          title: ${{ steps.bumpver.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
