name: Bump Version and Tag

on:
  push:
    branches:
      - master

jobs:
  bump_semantic_version:
    name: Bump Semantic Version & Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Bump version, push tag, and generate CHANGELOG.md
        id: bumpver
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version-file: pyproject.toml
          version-path: 'project.version'
      - name: Create new milestone
        id: createmilestone
        uses: WyriHaximus/github-action-create-milestone@master
        with:
          title: ${{ steps.bumpver.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
