name: Bump Version and Tag

on:
  push:
    branches:
      - master

jobs:
  bump_semantic_version:
    name: Bump Semantic Version & Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Bump version and push tag
        id: bumpver
        uses: mathieudutour/github-tag-action@v4
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          create_annotated_tag: true
      - name: 'Create new milestone'
        id: createmilestone
        uses: "WyriHaximus/github-action-create-milestone@master"
        with:
          title: ${{ steps.bumpver.outputs.new_tag }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
