name: Bump Version, Tag, and Cut Release PR

on:
  push:
    branches:
      - master

jobs:
  bump_semantic_version:
    name: Bump Semantic Version & Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Determine next version
        id: version
        uses: patrickjahns/version-drafter-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update VERSION and pyproject.toml file
        if: ${{ steps.version.outputs.next-version != '' }}
        run: |
          echo "${{ steps.version.outputs.next-version }}" > VERSION
          sed -i 's/\(^version =.*$\)/version = "${{ steps.version.outputs.next-version }}"/' pyproject.toml
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -a -m "Update VERSION and pyproject.toml" && echo "do_push=1" >> $GITHUB_ENV

      - name: Update CHANGELOG.md and cut release PR
        if: env.do_push == 1
        uses: patrickjahns/chlgr@v1
        with:
          release-version: ${{ steps.version.outputs.next-version }}
          release-branch: "release/v${{ steps.version.outputs.next-version }}"

      - name: Create new milestone
        id: createmilestone
        if: ${{ steps.version.outputs.next-version != '' }}
        uses: WyriHaximus/github-action-create-milestone@master
        with:
          title: "v${{ steps.version.outputs.next-version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
